#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""第三批扩量：data/seed/part-14..15.jsonl，共 80 条带 input 长答案。
code-zh 40（真实代码/报错为 input）+ terminal 40（命令输出/场景为 input），
output 150-500 字，instruction/output 全网唯一（预加载老数据校验）。
运行：python3 scripts/gen_long_1415.py && python3 scripts/make_dataset.py
"""
import json, os, glob
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEED = os.path.join(ROOT, "data", "seed")

SEEN_I, SEEN_O = set(), set()
for f in glob.glob(os.path.join(SEED, "part-*.jsonl")):
    if os.path.basename(f) in ("part-14.jsonl", "part-15.jsonl"):
        continue  # 本批输出，跑完重写，不参与去重基线
    for l in open(f, encoding="utf-8"):
        if l.strip():
            r = json.loads(l)
            SEEN_I.add(r["instruction"].strip())
            SEEN_O.add(r["output"].strip())

N = {"code-zh": 80, "terminal": 125}
parts = {}
def add(part, cat, ins, out, inp):
    ins, out, inp = ins.strip(), out.strip(), inp.strip()
    assert ins and out and inp, f"空字段: {ins[:30]}"
    assert 150 <= len(out) <= 2000, f"长度{len(out)}: {ins[:30]}"
    assert ins not in SEEN_I, f"instruction重复: {ins[:40]}"
    assert out not in SEEN_O, f"output重复: {out[:40]}"
    SEEN_I.add(ins); SEEN_O.add(out)
    N[cat] += 1
    parts.setdefault(part, []).append(
        {"id": f"{cat}-{N[cat]:03d}", "category": cat,
         "instruction": ins, "input": inp, "output": out})

P14 = [
("这段取最后一个元素的代码为什么报错",
 "a = [1, 2, 3]\nprint(a[3])\n# IndexError: list index out of range",
 "下标从 0 开始，长度 3 的列表只有 a[0]、a[1]、a[2]，a[3] 越界。取末尾直接用 a[-1]，取首尾用 a[0] 和 a[-1]，从根上避开长度换算。防御写法是先判断：if a 再取，或 if i < len(a)。循环里尤其别用 range(len) 配 a[i+1]，末尾必炸，改成 zip(a, a[1:]) 配对遍历。"),
("嵌套字典取值怎么写才不炸 KeyError",
 "cfg = {'db': {'host': 'x'}}\nprint(cfg['db']['port'])\n# KeyError: 'port'",
 "链式中括号只要一环缺键就炸。只读场景用分层 get：cfg.get('db', {}).get('port', 5432)，缺哪环都不炸且有默认值。需要区分缺失和 None 就用哨兵：_M = object()，v = d.get(k, _M)，is _M 即缺键。写配置解析时把必填键集中校验一次，报错列出缺了谁，别让 KeyError 在深夜调用链里爆。"),
("json.loads 遇到坏数据就崩，怎么兜底",
 "import json\ndata = json.loads(open('a.json').read())\n# json.decoder.JSONDecodeError",
 "输入不可信，解析必须 try：try 解析 except JSONDecodeError 给默认值并记下原文前 100 字和文件名。批量处理 JSONL 时逐行 try，一行坏只跳过一行，最后报坏行数。根治靠上游：写文件用 json.dump 保证格式，读之前先 os.path.getsize 排查空文件，空文件 loads 必炸。"),
("requests 请求偶发卡死，怎么加固",
 "import requests\nr = requests.get('http://api/x')\n# 偶发几分钟无返回",
 "默认 requests 无超时，一次慢响应拖死全程。get 加 timeout=(3, 10)（连接 3 秒、读取 10 秒），外层抓 RequestException。读接口再包一层重试：3 次、指数退避 1/2/4 秒，只重试超时和 5xx，4xx 直接抛。重度依赖加熔断计数，连续失败 10 次直接快速失败并告警，别让重试雪球越滚越大。"),
("用 shell=True 拼命令有什么风险，怎么改",
 "import subprocess, sys\nsubprocess.run('grep ' + sys.argv[1] + ' app.log', shell=True)",
 "用户输入拼进 shell 就是注入：传 `a; rm -rf ~` 直接执行。改法是 argv 列表：subprocess.run(['grep', kw, 'app.log'])，不经 shell 解析，特殊字符只当纯文本。必须用管道就用 Python 侧处理，或 shlex.quote 包裹变量。记住：shell=True 只在命令完全硬编码时用。"),
("CSV 有 2GB，一次读入内存爆了怎么办",
 "import csv\nrows = list(csv.DictReader(open('big.csv')))\n# MemoryError",
 "改流式：for row in csv.DictReader(f) 逐行处理，内存只占一行。需要聚合就边读边累加字典，结束再输出。编码先确认：utf-8-sig 去 BOM，报错 UnicodeDecodeError 就 errors='replace' 先跑通再修源。超大文件配 tqdm 看进度，长任务中途可断点：每 N 行 checkpoint 已处理行号。"),
("循环里查数据库越跑越慢，是什么问题",
 "for u in users:\n    print(db.query(Order).filter_by(uid=u.id).all())\n# 1+N 查询",
 "典型 N+1：1 次查用户加 N 次查订单。改 join 一次取出：query(Order).join(User) 或 selectin 预加载，N 次变 2 次。先 EXPLAIN 确认索引命中，条件列没索引加索引。分页别 OFFSET 深翻，用 id 游标。记住口诀：循环里出现查询，先想能不能提到循环外。"),
("这个邮箱正则为什么放行了非法地址",
 "import re\nre.match(r'.+@.+\\..+', 'a@b@c.d')\n# 匹配通过",
 ".+ 太贪还允许 @ 出现多次。够用版：^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$，保证恰好一个 @ 且有点。想再严用 email-validator 库，别自己叠长度规则。最终校验靠发验证邮件，正则只拦格式离谱的。测试备正反两例：正常地址过，a@b@c.d 和带空格的不过。上线前把正反用例写进单测，回归跑一遍，以后改规则不心慌。"),
("装饰器把函数名弄丢了，help 全乱，怎么修",
 "def deco(f):\n    def w(*a, **k): return f(*a, **k)\n    return w",
 "w 包裹后 __name__ 变成 w，日志和文档全错。标准修法：from functools import wraps，给 w 加 @wraps(f)，名字文档签名全保留。带参装饰器多一层闭包，每层都要 wraps。顺带：装饰器里别吞异常，日志打清 f.__name__，否则报错堆栈看不出原函数。"),
("多线程跑 CPU 任务反而更慢，为什么",
 "import threading\nts = [threading.Thread(target=calc, args=(x,)) for x in xs]\n[t.start() for t in ts]; [t.join() for t in ts]",
 "GIL 锁死：CPU 密集任务多线程还是串行，还多线程切换开销。CPU 密集换 multiprocessing 真并行，IO 等待才用线程或 asyncio。先 profile 确认瓶颈真是 CPU，别凭感觉换。进程间传大对象走共享内存或分块，pickle 来回拷同样慢。换之前先单线程 benchmark 留底，换之后同条件再测，数字证明方向对了再提交。"),
("pandas 报 SettingWithCopyWarning，怎么改对",
 "import pandas as pd\ndf[df.a > 0]['b'] = 1\n# SettingWithCopyWarning",
 "链式赋值改的是临时副本，原表没变还告警。改 .loc 一次定位：df.loc[df.a > 0, 'b'] = 1。需要副本就先 df2 = df[cond].copy() 再改，意图明确。记住：方括号连写两次就是坑，loc 一次写完。告警出现就当 bug 修，别 filterwarnings 掩耳盗铃，掩掉的都是未来的坑。"),
("pip 装包装到一半冲突报错，怎么隔离",
 "pip install a b\n# ERROR: pip's dependency resolver ... conflict",
 "系统 python 装包互相打架。项目级隔离：python -m venv .venv 切进去再装，冲突只影响本项目。锁版本用 pip freeze 定requirements，CI 按锁文件重装。库开发别 pin 死版本，用范围；应用部署 pin 死，保证可复现。修完 pip check 验证无冲突，再 freeze 锁文件，CI 按锁重装保证可复现。"),
("Docker 构建每次都重下依赖，怎么加速",
 "FROM python\nCOPY . /app\nRUN pip install -r requirements.txt",
 "COPY . 在前，改一行代码就使依赖层缓存失效。调顺序：先 COPY requirements 再 pip install，最后 COPY 源码，依赖层只在依赖变时重建。再开 BuildKit 缓存挂载，pip 走缓存目录。验证：改个注释重建，看 Using cache 是否命中依赖层。优化完对比构建时长，依赖层命中时只剩秒级，镜像体积也顺手看一眼。"),
("rebase 和 merge 到底用哪个",
 "$ git merge feature\n# 历史分叉，log 难读",
 "个人分支同步主干用 rebase，历史成直线好读；公共分支合入用 merge 保留节点。rebase 后必须 force-push 自己分支，公共分支禁 rebase，改写历史会坑队友。记一句：rebase 整理自己的，merge 合并大家的。团队先统一约定写进 CONTRIBUTING，新人不用猜，review 时也不用吵。"),
("pytest 每个用例都要建临时文件，怎么写",
 "def test_a():\n    open('/tmp/t.txt','w').write('x')\n# 用例互踩，并行必炸",
 "用 tmp_path fixture：def test_a(tmp_path)，路径自动隔离并行不打架。需要复用的前置抽成 fixture 放 conftest.py，scope 按需设。外部资源（DB/网络）用 monkeypatch 或 mock 替掉，单测不碰真环境。fixture 粒度越小越好，一个只做一件事，组合使用比大而全好维护。"),
("print 调试上线前怎么换成日志",
 "print('got', x)\n# 上线一堆 stdout",
 "换 logging：logging.basicConfig(level=INFO) 起步，模块里 getLogger(__name__)。级别分清：debug 排错、info 关键路径、warning 可恢复异常、error 要人看。生产加 dictConfig 配文件轮转和格式，print 只留 CLI 输出。"),
("argparse 子命令怎么写",
 "python tool.py run --fast\n# 想做 git 式子命令",
 "add_subparsers(dest='cmd') 加子解析器，每个子命令 set_defaults(func=...) 绑定入口，主函数调 args.func(args)。required=True 防无参空转，help 写清每个子命令一句话。子命令超 3 个就拆模块，别堆一个文件。每个子命令配 --help 一句话说明，用户不看文档也能上手，这就是门面。"),
("copy 一份配置改完两份一起变，为什么",
 "a = {'x': [1]}\nb = a.copy()\nb['x'].append(2)\n# a 也变了",
 "浅拷只拷第一层，嵌套列表还是同一引用。用 copy.deepcopy 全拷，或重构掉共享：配置 freeze 成不可变。判断标准：改完 b 跑单测断言 a 不变。性能敏感就只深拷要改的那支，别整棵拷。修完加回归单测：改 b 断言 a 不变，以后谁引入共享一个测一个准。认准一条：嵌套结构赋值先想共享，出 bug 先查这层。"),
("datetime 存库差 8 小时，怎么根治",
 "from datetime import datetime\ncreated = datetime.now()\n# 存进去晚 8 小时",
 "naive 时间无时区，存取按不同时区解读就差 8 小时。根治：全链路 UTC，datetime.now(timezone.utc)，展示层再转本地。库字段用 timestamptz，老数据一次性迁移。测试固定两个时区跑一遍，夏令时边界重点看。迁移老数据前先备份，灰度切一小批验证，时间 bug 回滚比修更贵。"),
("requests 每次建连慢，怎么复用",
 "for u in urls:\n    requests.get(u)\n# 每次握手",
 "Session 复用连接池：s = requests.Session()，循环里 s.get，TCP 握手一次。配 HTTPAdapter 设 pool_connections 和重试，超时照旧加。长任务结束 s.close()，或 with 包裹。压测对比建连时间，池化后延迟掉一半常见。连接池大小按并发配，默认 10 不够就调 Adapter，别让排队抵消池化收益。"),
("递归 5000 层爆栈，怎么改迭代",
 "def f(n): return f(n-1) + 1\nf(5000)\n# RecursionError",
 "改显式栈：stack = [init]，while stack 弹栈处理，结果累加。必须递归就 sys.setrecursionlimit 调高加分治降深度，但栈照样吃内存。优先迭代：状态放栈里，逻辑和原来递归体一一对应，单测对拍新老实现。改完对拍：同输入新老实现输出一致，边界全覆盖再删老代码。迭代版逻辑和递归体一一对应，改完读一遍确认无遗漏。"),
("大文件处理内存一点点涨，是哪漏了",
 "for line in open('f'):\n    buf.append(parse(line))\n# 常驻增长",
 "buf 无限攒就是漏：边读边写边清，或分块刷盘。生成器 yield 逐条吐，下游消费完即释放。定位用 tracemalloc 抓快照对比，看哪类对象在涨。记住：流式管道里不许出现无界 list。修完跑全量看 RSS 曲线平稳，再压两倍数据验证，一次跑完证明不了。定位到攒数据的容器，改成流式吐出，复测曲线平稳才算修好。"),
("lru_cache 报 unhashable type，怎么修",
 "from functools import lru_cache\n@lru_cache\ndef f(d): return d['x']\n# TypeError: unhashable",
 "dict 不可哈希进不了缓存。调用侧转 frozenset(d.items()) 或 json.dumps(d, sort_keys=True) 当 key。参数实在复杂就手写 dict 缓存，key 用自己定的字符串。缓存先定失效策略，lru 配 maxsize 防无限涨。缓存 key 必须稳定可复算，时间戳随机数进 key 等于没缓存，review 重点看。"),
("多进程传大对象慢，怎么优化",
 "from multiprocessing import Pool\nPool().map(f, big_list)\n# pickle 来回拷",
 "跨进程靠 pickle 序列化，大对象拷两次。改分块传索引、子进程自己读文件，或共享内存 RawArray。只读大模型放 fork 后全局变量，Linux 写时复制零拷贝。先量：time 看序列化占比，占比小别折腾。分块粒度按核数配，块太小调度开销大，压测找 sweet point 再定。实在降不下来就换思路：子进程直读文件，传路径不传数据。"),
("写一半的配置文件被读到，怎么原子化",
 "open('c.json','w').write(new)\n# 崩溃留半截文件",
 "写临时再 os.replace：open(tmp).write + fsync + os.replace(tmp, target)，读者要么旧要么新。Windows 上 replace 同目录才原子，跨盘先拷。配 systemd 的服务重载前校验 JSON 合法，坏文件直接拒收。替换后读回校验一次，坏文件拒收并告警，原子写入加校验才是闭环。"),
("SIGTERM 来了服务直接被杀，怎么做优雅退出",
 "import signal\n# 直接跑，无信号处理",
 "signal.signal(SIGTERM, handler)，handler 里置 stop 标志，主循环收尾：停接新请求、等在途完成（设 deadline）、关连接池。再配 SIGINT 同逻辑方便 Ctrl+C。K8s 给 terminationGracePeriod，超时还不退就被杀，收尾必须限时。"),
("asyncio.gather 一个炸全炸，怎么隔离",
 "await asyncio.gather(*tasks)\n# 一个异常全抛",
 "gather(return_exceptions=True) 把异常当结果收，逐个 isinstance 判。需要限时包 wait_for，超时任务 cancel。结构化并发用 TaskGroup，退出自动等齐。记住：异常是数据，先收齐再统一处理。收齐结果统一打日志，失败任务带输入上下文，重试只重试失败的几个。"),
("资源释放总漏写，有什么固定写法",
 "f = open('x')\n... # 异常就漏关",
 "with 语句包住：open、锁、连接、临时目录全有上下文管理器。自家资源写 __enter__/__exit__ 或 contextlib.contextmanager。原则：申请和释放写在一起，别靠人记关闭。团队约定：申请资源的函数必须同时给出释放方式，review 见裸 open 直接打回。申请和释放在同一屏写完，隔着几十行的关闭必漏，这是经验之谈。"),
("Optional 到底什么时候用",
 "def f(x) -> int:\n    return None if x < 0 else x",
 "可能返回 None 就写 Optional[int]，调用方被迫处理空值，mypy 提前抓。内部确定非空别加，加了等于狼来了。老代码渐进加：先公共函数签名，再内部。对外 API 签名先加，内部实现后补，mypy 开 strict 让机器替你检查。标了就要处理，不处理不如不标，空值检查前置别拖到深夜报错。"),
("dataclass 默认空列表报错，怎么写",
 "@dataclass\nclass C:\n    xs: list = []\n# ValueError: mutable default",
 "field(default_factory=list)，每个实例独立新列表。其他可变默认同理，tuple/str 才可直接给。顺带 frozen=True 做不可变配置，改字段直接抛错。顺手把同文件其他可变默认扫一遍，同类 bug 一般扎堆出现。改完把实例隔离测一遍，两个实例互不影响才算真修好，这是最基本的自检。"),
("排序结果不稳定，顺序乱跳，为什么",
 "data.sort(key=lambda r: r['score'])\n# 同分顺序每次不同",
 "Python sort 本身稳定，同分保持原序；乱跳说明输入顺序在变（set 遍历、并发写入）。要确定性加第二关键字：key=(score, id)。展示前全排序，别依赖插入序。修完加断言锁住顺序，随机输入跑 100 次，确定性问题靠重复验证。根因多半在输入源，排序前先把输入顺序固定，展示层再全排序。"),
("手写二分总差一，怎么写对",
 "lo, hi = 0, len(a)\nwhile lo < hi:\n    mid = (lo+hi)//2\n# 边界总错",
 "左闭右开模板背下来：a[mid] < t 则 lo = mid+1，否则 hi = mid，结束 lo 即插入点。bisect 模块就是这个实现，能调库就调库。测试三例：空、单元素、目标在两端。模板背下来默写三遍，空集单元素两端各测，边界 bug 靠用例杀不靠眼看。调库永远优先，bisect 经过千锤百炼，手写只留给面试和理解原理。"),
("手写 LRU 缓存怎么做",
 "# 需要定容淘汰",
 "OrderedDict 版：get 时 move_to_end，put 超容 popitem(last=False)。dict+双链表是面试版，生产直接 lru_cache。淘汰策略先说清：LRU 还是 TTL，不同场景不同命。生产直接调库，手写只用于面试和理解原理，线上别重复造轮子。容量和淘汰策略按业务定，缓存不设上限等于内存泄漏，迟早爆。"),
("接口限流怎么做才不误伤",
 "# 无限流，并发一高就挂",
 "令牌桶：每秒加 N 个令牌，桶满丢弃，请求先拿令牌。网关层限 IP+用户两级，业务层限重操作。超限返回 429 带 Retry-After，客户端退避重试。先监控再收紧，阈值拍脑袋必误伤。阈值先宽后严，灰度观察一周再收紧，误伤一次信任掉一截。限流返回体带剩余配额，客户端看得懂才不会盲重试，文档写清阈值。"),
("重试逻辑怎么写才完整",
 "try:\n    call()\nexcept:\n    call()\n# 无脑重试",
 "完整四件：只重试可重试异常（超时/5xx），指数退避 1/2/4 秒加抖动，最多 3 次，写操作先保证幂等。裸 except 连 4xx bug 都重试，越错越忙。最后一次失败抛出来并告警，别吞。重试参数放配置里可调，线上调阈值不用发版，半夜救火时你会感谢自己。重试和幂等是一对，缺了幂等的重试是灾难，先保证做了同样结果不变。"),
("CSV 中文打开乱码，怎么处理",
 "open('a.csv').read()\n# UnicodeDecodeError / 乱码",
 "Excel 出的 CSV 带 BOM：open(encoding='utf-8-sig') 自动去。先 file/chardet 确认编码再定，别 latin-1 蒙混。写侧统一 utf-8-sig，读侧 try utf-8-sig  fallback 备选。管道里全程 UTF-8，locale 也检查。"),
("日志文件无限涨，怎么轮转",
 "logging.basicConfig(filename='a.log')\n# 单文件涨到几十G",
 "RotatingFileHandler 按大小切（maxBytes+backupCount），或 TimedRotating 按天切。生产再配 find 删 30 天前，磁盘双保险。JSON 日志配好格式再轮转，半截 JSON 解析不了。轮转配好后看一周磁盘曲线，平稳才是真修好，继续涨说明级别没调对。"),
("环境变量没配服务照样起，线上炸了怎么办",
 "port = os.environ.get('PORT', '8080')\n# 缺键也跑",
 "启动即校验：REQUIRED 列表缺一不可，缺就打印缺谁并 exit 1。默认值只给本地开发用，生产配置显式给。配 .env.example 当清单，新人照着填。把校验做成启动第一步，失败 exit 1 让编排器拉起，别带病运行。本地开发用宽松默认，生产强制显式配置，环境区分靠变量名后缀，出事就是大事。"),
("单测依赖外部接口，怎么 mock",
 "def test_pay():\n    assert pay() == True\n# 真调支付",
 "unittest.mock.patch 替掉 requests.post，返回值写死成功失败两例。断言调过：assert_called_with 核对参数。集成测试另起目录打标记，单测永远离线可跑。mock 数据和线上结构保持同步，接口变了单测跟着变，不然自欺欺人。集成测试另起目录 nightly 跑，单测永远离线秒级，这是铁律。"),
("新功能慢了 3 倍，怎么定位",
 "# 体感慢，无数据",
 "先复现量化：time 或 cProfile 抓热点，改前 benchmark 留底。八成是循环里加了 IO 或 N+1，提到循环外。优化完同条件再测，数字说话。一次只改一处，绿了再动下一处。定位到行先看能不能删代码，不行再优化，最快的代码是不跑的代码。热点找到后评估调用必要性，能缓存就缓存，能批量就批量。"),
]
for q, inp, a in P14:
    add(14, "code-zh", q, a, inp)

P15 = [
("df 显示 / 满了，下一步怎么做",
 "Filesystem      Size Used Avail Use% Mounted on\n/dev/sda1        50G   48G  2G  96% /",
 "先 du -sh /* 找哪个目录大，再进目录 du -sh * 下钻。大头一般是日志、备份、docker。清缓存旧日志，不动数据。删被进程占着的文件空间不释放：lsof | grep deleted 找出来重启进程。治本：日志轮转加配额，监控 80% 告警。清理完设 80% 告警线，下次提前处理，救火不如防火。"),
("端口 8080 起不来，怎么确认被谁占了",
 "$ python app.py\nOSError: [Errno 98] Address already in use",
 "ss -lntp | grep 8080 或 lsof -i :8080，看 PID 和进程名。开发自启的旧进程 kill 掉，线上服务就换端口。根治：应用支持 PORT 环境变量，启动脚本先检查端口再跑。查到僵尸进程顺手看为什么没退出，杀进程治标，修退出逻辑治本。开发环境配端口自动递增，占用就换下一个，省得天天查。"),
("free 显示内存快满了，怎么看元凶",
 "              total  used  free\nMem:           3.7G  3.4G  100M\nSwap:          1G   900M   100M",
 "ps aux --sort=-%mem | head 揪 RES 最高的，docker 用 docker stats 看容器。swap 满说明物理内存早不够，加内存或限额。应急：重启泄漏进程，治本：配 memory limit 和 OOM 告警。找到元凶先分清泄漏还是正常增长，泄漏修代码，正常增长加内存或限额。"),
("日志里报错前后 5 行怎么捞",
 "$ grep ERROR app.log | head\n# 只有报错行，没上下文",
 "grep -n -C5 ERROR app.log，一次给前后 5 行加行号。-n 定位，-C 给上下文，--line-buffered 管道实时。先看第一次报错，后面多半是连锁。捞到第一现场先存档再动手，修完回看确认报错消失，形成闭环。行号记下来直接跳过去看，比翻页快十倍，-n 参数天天用，效率翻倍。"),
("几百个文件批量改后缀，怎么做才安全",
 "$ ls *.txt | wc -l\n300",
 "for f in *.txt; do mv \"$f\" \"${f%.txt}.md\"; done。引号防空格，先把 mv 换 echo 预演名单。300 个以上用 rename 或 mmv 一行搞定。改完 git status 抽查几个，错了好回滚。改完抽查 10 个文件内容无损，大批量操作抽查是底线。"),
("找出 7 天没动的大文件，怎么写",
 "$ du -sh *\n# 太多看不过来",
 "find . -type f -mtime +7 -size +100M -exec ls -lh {} \\;，时间和大小双条件。先 -ls 预览名单，确认再 -delete。放 cron 每周跑，报告发邮件别直接删。删之前和业务方确认一遍，删错的恢复成本比确认高十倍。名单先存文件再删，删错了按名单找备份恢复，留一手总没错。"),
("两台机器同步代码目录，怎么做",
 "$ scp -r proj user@b:/srv\n# 每次全量，好慢",
 "换 rsync -avz --delete：增量只传差异，-n 先 dry-run 看方向。--delete 会删对端多余文件，方向错了是灾难，预演必做。长期同步加 --exclude 排除 .git 和日志。同步完两边各跑一遍单测，文件一致不代表服务一致。敏感文件排除在外，.env 传过去就是事故，exclude 列表写进脚本。"),
("ssh 免密登录配完还让输密码，怎么查",
 "$ ssh-copy-id user@h\n$ ssh user@h\npassword:",
 "三处：服务端 sshd 开没开公钥认证，~/.ssh 700、authorized_keys 600，公钥是否完整一行。ssh -v 看卡在哪：publickey 跳过就是服务端拒，permission 就是权限。修好后从跳板机完整走一遍，链路每段都通才算完。权限修完重连验证，644 的 authorized_keys 是最常见的坑，没有之一。"),
("cron 任务手动行、定时不行，为什么",
 "0 * * * * /home/u/job.sh >>/tmp/j.log 2>&1\n# 手动跑OK",
 "cron 环境极简：PATH 只有基础，脚本内写绝对路径，source 该 source 的。百分号要转义，环境变量脚本开头重设。日志重定向看报错，别黑盒。修完等一个整点看日志验证，cron 问题必须等周期，别改完就走。脚本开头重设 PATH 和关键变量，别指望 cron 继承你的环境，这是 cron 第一坑。"),
("tar 包解开文件散一地，怎么避免",
 "$ tar -xzf a.tgz\n# 当前目录多了几十个文件",
 "先 tar -tzf 列内容，有散文件就 mkdir 解到空目录：tar -xzf a.tgz -C dir。绝对路径条目更危险，解前必看名单。习惯：下载的包先列后解。养成先列后解的习惯，陌生包一律隔离目录，这类灾难经历一次就够。解完 ls 确认结构再挪位置，散文件挪起来比重解还麻烦，别偷懒，这是铁律。"),
("curl 返回 500，怎么继续查",
 "$ curl -s http://api/x\n{\"error\":\"boom\"}\n# 只有一句",
 "curl -s -w '\\n%{http_code} %{time_total}\\n' 看状态码和耗时，再 -v 看请求头。500 是服务端问题，拿 request-id 查服务端日志。curl 只证明现象，根因在服务端。把 request-id 记下来再找服务端同学，有 id 快十倍，没 id 只能大海捞针。"),
("jq 取嵌套数组里的名字，怎么写",
 "$ cat data.json\n{\"data\": {\"list\": [{\"name\": \"a\"}]}}",
 "jq -r '.data.list[].name'。先裸 jq . 看结构，再一层层加 filter，-r 去引号好进管道。不确定字段在不在用 .data?.list[]? 防 null 炸。filter 写进脚本加注释，下次直接复用，命令行历史靠不住。字段可能缺失就加问号防爆，线上 JSON 结构天天变，防御性写法保命。"),
("sed 批量改配置，怎么不翻车",
 "$ sed -i 's/8080/9090/g' *.conf\n# 改完服务起不来",
 "先不加 -i 跑一遍看输出，确认再 -i.bak 备份改。正则先在单个文件试，通配符别一次全改。改完 diff 对一份，服务重载前 nginx -t 之类先验。改完逐台重载验证，别一次性全改，灰度思维用在运维上同样有效。改之前 cp 一份带日期后缀，回滚只要一条 mv 命令，这就是安全感，有备无患。"),
("awk 统计第二列求和，怎么写",
 "$ cat num.txt\n10 x\n20 y",
 "awk '{s+=$2} END {print s}'，分隔符特殊加 -F。表头先 NR>1 跳过，空行 NF==0 跳过。大文件 awk 一遍过，别 cat 进管道再算。结果和源系统对一遍数，管道算错一位就是事故，对账是底线。金额统计用整数分计算，浮点累加差一分钱对账能对到哭，一分都不能差，差一分都不行。"),
("几千个小任务并行压满 CPU，怎么做",
 "$ for f in *.log; do gzip $f; done\n# 串行太慢",
 "find . -name '*.log' -print0 | xargs -0 -P$(nproc) -I{} gzip {}。-P 并行数配 nproc，-0 防空格文件名。先拿 10 个试，IO 瓶颈加并行也没用，看 iostat。跑完抽查失败率，xargs 默认继续执行，失败任务要单独重跑。并行数按核数配，IO 密集可超配，跑起来看 load 再调。"),
("tmux 里跑的任务，断网重连怎么找回",
 "$ tmux ls\nno server running",
 "TMUX_TMPDIR 变了或 server 被杀：固定 export TMUX_TMPDIR 再起会话。起名 tmux new -s work，attach -t work 直达。关键任务放 systemd，不是 tmux，tmux 只保交互。找回后先看任务还在不在跑，再看输出有没有报错，重连不等于正常。"),
("git 合并冲突了，标准动作是什么",
 "<<<<<<< HEAD\nkeep A\n=======\nkeep B\n>>>>>>> feat",
 "git status 看冲突文件，逐个二选一或手合成，git add 标记解决，commit 收尾。难抉择找对方对齐，别猜。完事跑一遍测试，冲突解决常带 bug。解决完跑全量测试再推，冲突解决引入的 bug 比冲突本身更常见。冲突文件逐个来，别批量 accept，批量点掉的都是未来的 bug，慢就是快。"),
("分支删错了，刚提交还在吗",
 "$ git branch -D feat\n# 手滑",
 "在，reflog 里：git reflog 找 feat 最后的 sha，git branch feat <sha> 重建。推过的远端也有。30 天内基本可救，gc 过就没了。记住：-D 前先看 merged 没。救回来立刻推远端备份，本地分支说没就没，远端才是保险箱。平时多推远端，本地只是草稿纸，推上去才算存档。"),
("容器一启动就退出，怎么查",
 "$ docker ps\n# 空的，run 完就没",
 "docker ps -a 看退出码，docker logs 看最后输出，八成是 CMD 报错或配置缺。docker inspect 看挂载和环境变量。本地 docker run --rm -it 进镜像手动跑一遍复现。查到原因把健康检查加上，下次起不来直接报原因，不用再翻日志。CMD 用 exec 格式当前台进程，shell 包一层信号收不到，退出码都看不懂。"),
("怎么进运行中容器拿文件",
 "$ docker exec -it web sh\nOCI runtime exec failed: no sh",
 "distroless 没 shell：docker cp web:/path /tmp 拷出来看。调试换带 shell 的 debug 镜像。设计上容器就该不可进，日志外打、文件外挂。拿出来把日志外挂出去，下次不用再进容器，设计上容器就该是黑盒。常用路径记下来，下次直接 cp，少进一次是一次，这是正道。"),
("npm 装包巨慢，怎么换源",
 "$ npm install\n# 几分钟不动",
 "npm config set registry https://registry.npmmirror.com，装完测个小包验证。CI 里写 .npmrc 跟着仓库走，别各人本地配。源抽风先切回官方排除法。换源后删锁重装一次，保证依赖树在新源下完整，别混源。项目级 .npmrc 跟着仓库走，换电脑不用重配，团队统一才省心。"),
("node 版本太老跑不动新语法，怎么升",
 "$ node -v\nv12.22.0",
 "nvm 装新版切过去，或 pkg 重装（Termux）。项目 engines 声明 >=18，CI  enforcing。升完删 node_modules 重装，原生模块要重编。升级后全量测试跑一遍，原生模块重编，大版本升级必有惊喜。engines 字段声明版本，装错直接报错，比运行时报错强一百倍。"),
("目录权限被改成 777，怎么收敛",
 "$ ls -ld data\nrwxrwxrwx",
 "目录 755 文件 644 收敛：find data -type d -exec chmod 755 {} \\;，文件 644。777 先查谁改的，Web 目录可写是入侵入口。改完服务重启验证，别只看 ls。收敛后查审计日志找元凶，人不找到下次还会被改回去。Web 目录重点查，可写目录是入侵入口，收敛完顺手看访问日志。"),
("软链断了，批量怎么找",
 "$ ls -l lib/\nxxx -> /opt/old/yyy（红字）",
 "find lib -xtype l 列出断链，ls -l 看原指向。批量重指用 ln -sfn，或 sed 改一批量。/opt 搬家是常见病因，部署脚本里把路径变量化。修完把路径写进配置别硬编码，这次搬家下次还搬，变量化一劳永逸。新部署用相对路径软链，搬家不断，这是老运维的习惯，一次到位，这招要记牢。"),
("磁盘 IO 高，服务卡，怎么确认",
 "$ uptime\nload average: 12.0\n# CPU 不高但卡",
 "iostat -x 看 %util 和 await，util 满就是盘瓶颈。再 iotop 揪进程。治标：降刷盘频率；治本：上 SSD 或读写分离。云盘先看配额和 burst。确认瓶颈先限流保命，再扩容根治，顺序反了扩容也救不了。云盘看 burst 余额， burst 用完限速，卡的原因八成在这，先看余额再动手。"),
("服务时通时断，怎么看网络路径",
 "$ ping api\n# 偶发丢包",
 "mtr 看每跳延迟丢包，定位是哪段。云上先查安全组和 NAT，再抓包。ping 只能看通断，mtr 才看得清路径。定位到故障段先截图留证，再找对应负责人，证据比描述管用。mtr 跑 100 个包再下结论，几个包的丢包可能是 ICMP 限速，不是真故障，结论才站得住，跑够包数再下结论，样本太少全是误判。"),
("证书还有几天过期，怎么查",
 "$ curl https://x\ncurl: certificate expired",
 "openssl s_client -connect x:443 | openssl x509 -noout -dates 看起止。剩 30 天就续，ACME 自动续加 reload 验证。过期先换证书再查别的，别绕路。查完把续期做成自动任务加告警，人工记日期必漏，这是血泪教训。多个域名写个循环批量查，输出表格贴到值班群，一目了然。"),
("nginx 改完配置怎么生效不断连",
 "$ nginx -s reload\n# 报错找不到 pid",
 "先 nginx -t 验语法，通过再 reload 热加载。找不到 pid 说明没在跑，先 start。reload 失败自动保旧 worker，别怕，但改前备份 conf 是习惯。reload 后 curl 几个关键路径验证，配置生效不等于业务正常。大改先在测试机验，生产 reload 选低峰期，习惯比技术重要。"),
("新服务怎么做开机自启",
 "$ ./app &\n# 重启就没",
 "写 systemd unit：ExecStart 指绝对路径，Restart=on-failure，enable 开机自启。enable 后 reboot 验证一次。日志走 journald，journalctl -u 看。配好后真重启一次验证，没验证过的自启等于没有，演练要动真格。unit 文件进版本库，换机器直接拷过去，文档和配置同步才不丢。"),
("journal 日志把盘写满，怎么瘦身",
 "$ du -sh /var/log/journal\n4G",
 "journalctl --vacuum-size=500M 立刻瘦身，再 /etc/systemd/journald.conf 限 SystemMaxUse。治标加治本，监控 80% 告警。瘦身后看一周曲线确认平稳，配额加告警双保险，别只治一次。治本是降日志级别，debug 别上生产，级别错了多少配额都不够。"),
("ssh 端口被扫爆，日志刷屏怎么办",
 "$ journalctl _COMM=sshd | tail\nFailed password × 1000",
 "改端口加 fail2ban 限频，关密码只留公钥。三件套缺一不可，只改端口没用，扫描器扫全端口。fail2ban 配好先自己试错 3 次看封不封。规则加上后自己故意输错 3 次验证，别等真攻击来了才发现没生效。公钥登录是根本解，密码迟早被撞出来，能关就关，长痛不如短痛，早关早清净，密码登录留着就是隐患。"),
("怎么看谁登录失败最多",
 "$ lastb | head\n# 一堆未知用户",
 "lastb 看坏登录，journalctl _COMM=sshd grep Failed 看来源 IP。配 fail2ban 自动封，阈值别太敏感误伤自己。看完把高频 IP 封了，剩下的配告警阈值，天天人肉看迟早会漏。确认是自己人就加白名单，别把自己锁外面，血泪教训，教训要记牢，别嫌麻烦，安全无小事。"),
("定时备份脚本怎么写才完整",
 "# 每天备份 /srv",
 "tar -czf /bak/$(date +%F).tgz /srv，只留 7 份：find /bak -mtime +7 -delete。备份完校验 tar -tzf 列得出，加恢复演练。脚本进 cron，日志重定向，失败发告警。脚本写完当月就做一次恢复演练，没演练的备份等于心理安慰。备份日志每天看一眼，没报错不等于成功，恢复演练才是金标准。"),
("怎么写一个端口健康检查脚本",
 "# 想监控 8080 活着",
 "curl -sf -m 5 http://127.0.0.1:8080/health || 告警。-f 让 500 也算失败，超时 5 秒。放 cron 每分钟，加连续失败 3 次才告警防抖。检查脚本自己也要日志，别黑盒。上线后故意停一次服务，看告警链路通不通，监控本身也要被监控。检查间隔按业务定，核心服务 1 分钟，边缘服务 5 分钟，别一刀切。"),
("git push 被拒非快进，怎么处理",
 "$ git push\nrejected - non-fast-forward",
 "git pull --rebase 同步，冲突修完 rebase --continue 再推。公共分支禁 --force。频繁被拒说明分支太久没同步，养成每天 rebase 一次。推上去确认远端历史符合预期，rebase 出错就地解决别拖到下次。每天开工先 pull --rebase，分支新鲜不惹事，好习惯省大麻烦。"),
("只想提交一半改动，怎么挑",
 "$ git diff --stat\n# 5 个文件，不想全交",
 "git add -p 逐块挑，unrelated 分两次提交。挑完 git diff --cached 核对暂存区，一坨提交 review 的人想打人。挑完跑一遍相关测试再推，半份提交也要保证能独立跑通。提交信息写清这次含什么不含什么，review 的人一眼看懂，这是基本礼貌，对自己负责也对 reviewer 负责。"),
("子模块拉不下来怎么办",
 "$ git submodule update --init\n# 空的",
 "加 --recursive，URL 变了先 git submodule sync。CI 里配 --recursive 拉取。能用 subtree 或单仓库就别子模块，坑比收益多。拉下来跑一遍构建验证，子模块版本和主仓是否匹配要亲眼确认。实在搞不定就 vendor 拷一份进来，简单可靠，适合小团队，别死磕。"),
("tag 打错了但已经推送，怎么办",
 "$ git push origin v1.0\n# 版本号打错",
 "删远端重打：git push --delete origin v1.0，本地删了重打再推。CI 已发版的别改 tag，发新版本。tag 是契约，推出去就别动。重打后通知所有用这个版本的人，tag 用出去就收不回，只能发新。版本号规范写进文档，vX.Y.Z 含义全员对齐，错一次长记性，规矩立下来错，规矩要立字为据。"),
("想看某个文件完整改动史，怎么做",
 "$ git log file\n# 只有提交列表",
 "git log -p -- file 看每次 diff，-S 关键字搜引入提交。blame 看行级作者，log -p 看演进。找回归用 bisect 二分，最快。看完把关键提交记下来，甩锅和学习都靠它，历史是最好的文档。大文件历史用 --follow 跟改名，不然一半记录丢了还不知道，好习惯，这是好习惯，受用终身。"),
("合并分支前怎么预演冲突",
 "$ git merge feat\n# 直接合了",
 "git merge --no-commit --no-ff 先合看状态，abort 可退。或建临时分支合，验证完再真合。预演 1 分钟，省 1 小时救火。预演没冲突也别大意，合完跑测试，语义冲突不报错只出 bug。长期分支每周合一次主干，冲突攒着只会更大，小步合并是正道，别等炸了再后悔，多一分钟预演少一小时救火。"),
]
for q, inp, a in P15:
    add(15, "terminal", q, a, inp)

for p in sorted(parts):
    fp = os.path.join(SEED, f"part-{p:02d}.jsonl")
    assert 14 <= p <= 15
    with open(fp, "w", encoding="utf-8") as f:
        for r in parts[p]:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"part-{p:02d}: {len(parts[p])}条")
print(f"新增合计 {sum(len(v) for v in parts.values())} 条")
