#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""200->700 扩量：生成 data/seed/part-06..part-13.jsonl，共 500 条新种子。
规范见 data/schema.md：id 全局唯一且前缀即分类，output<=2000 字符。
instruction 去空白哈希去重（make_dataset.py），本脚本额外保证 output 全网唯一。
风格：Muse Spark 短平快（先给答案，100-500字），code-en 用英文。
运行：python3 scripts/gen_expand_700.py && python3 scripts/make_dataset.py
"""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEED = os.path.join(ROOT, "data", "seed")

parts = {}
def put(part, row):
    parts.setdefault(part, []).append(row)

N = {"code-en": 0, "terminal": 0, "code-zh": 40, "code-agent": 30,
     "zh": 40, "en": 30, "tool-use": 15, "safety": 10,
     "translation": 10, "misc": 5, "math": 10, "reasoning": 10}
def nid(cat):
    N[cat] += 1
    return f"{cat}-{N[cat]:03d}"

SEEN_I, SEEN_O = set(), set()
def add(part, cat, ins, out, inp=""):
    ins, out = ins.strip(), out.strip()
    assert ins and out and len(out) <= 2000, f"bad: {ins[:30]}"
    assert ins not in SEEN_I, f"instruction重复: {ins[:40]}"
    assert out not in SEEN_O, f"output重复: {out[:40]}"
    SEEN_I.add(ins); SEEN_O.add(out)
    put(part, {"id": nid(cat), "category": cat, "instruction": ins,
               "input": inp, "output": out})

# ================= part-06: code-en x63 =================
P06 = [
("How do I fix 'IndexError: list index out of range' in Python?",
 "You're reading past the end. Print len(lst) first, then guard with `if i < len(lst)`. Last element is lst[-1], never lst[len(lst)].",
 "nums=[1,2,3]\nprint(nums[3])"),
("How do I read a big file line by line in Python?",
 "Iterate the file object directly: `with open('f.txt') as f:\n for line in f: ...`. Memory stays flat no matter the size.",
 ""),
("What does 'NoneType has no attribute' mean?",
 "A variable you assumed holds an object is None. Trace its assignment — usually a function missing return, or a failed dict lookup.",
 "user = find(id)\nprint(user.name)"),
("How do I parse JSON safely in Python?",
 "Wrap it: `try:\n data=json.loads(s)\nexcept json.JSONDecodeError:\n data={}`. Then read fields with .get(), never direct indexing on untrusted data.",
 ""),
("How do I add a timeout to requests.get?",
 "`requests.get(url, timeout=10)` plus `except requests.RequestException`. No timeout means one slow server hangs your whole program.",
 ""),
("How do I capture shell output from Python?",
 "`subprocess.run(cmd, capture_output=True, text=True, timeout=60)`. Pass argv as a list instead of shell=True to dodge injection.",
 ""),
("Why is my local module not importable?",
 "Python only searches sys.path. Run from the project root, check the filename spelling, and confirm the package has __init__.py if it's a package.",
 "import mymod  # ModuleNotFoundError"),
("How do I sort dicts in a list by one key?",
 "`sorted(rows, key=lambda r: r['age'])`, plus reverse=True for descending. Use r.get('age', 0) when some rows lack the key.",
 ""),
("How do I avoid KeyError on optional keys?",
 "Use d.get('k', default) for reads and d.setdefault(k, []) for accumulation. Exceptions should stay exceptional.",
 ""),
("How do I retry with backoff in Python?",
 "Loop 3 times, sleep 2**attempt seconds between tries, catch only the expected error. Log and re-raise after the final attempt.",
 ""),
("How do I debug a Node script that exits silently?",
 "Rerun with `node --trace-uncaught --unhandled-rejections=strict script.js`. Silent exits are almost always swallowed promise rejections.",
 ""),
("How do I read piped stdin in Node?",
 "Set encoding utf8, resume stdin, collect 'data' chunks, act on 'end'. For interactive prompts use readline, not raw stdin.",
 "echo hi | node cli.js"),
("How do I add a timeout to fetch?",
 "Race it: `Promise.race([fetch(url), delay(5000).then(()=>{throw new Error('timeout')})])`. Or use AbortController and clear the timer on success.",
 ""),
("How do I debounce a JS function?",
 "Store a timer id; each call clears it and sets a fresh setTimeout. The real function fires only after calls pause for `ms`.",
 ""),
("How do I deep-clone in modern JS?",
 "Call structuredClone(obj) — keeps Dates, Maps, nested arrays. The JSON round-trip trick silently drops functions and undefined.",
 ""),
("How do I fix 'Cannot read properties of undefined'?",
 "One link in the chain is undefined. Add `?.` to survive it, then console.log each step to find which one produced undefined.",
 "cfg.db.host"),
("How do I paginate an array in JS?",
 "`arr.slice(page*size, page*size+size)`. Clamp page to valid range; an empty slice simply means you're past the end.",
 ""),
("How do I limit concurrency for many async tasks?",
 "Run a pool of N workers pulling from a shared queue, or use p-limit. Promise.all on thousands of tasks exhausts sockets and memory.",
 ""),
("How do I validate email pragmatically in JS?",
 "Check shape with /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/ and confirm by sending a verification mail. No regex proves an address exists.",
 ""),
("How do I make a proper unique id in JS?",
 "Use crypto.randomUUID() where available. For short ids use crypto.getRandomValues — Math.random is neither unique nor secure.",
 ""),
("Why does my test pass locally but fail in CI?",
 "Top suspects: timing assumptions, timezone, test-order dependence, leftover files. Seed randomness and isolate state per test file.",
 ""),
("How do I fix 'port already in use' when starting a server?",
 "Find the holder with `lsof -i :3000` or `ss -lntp`, kill it or switch ports. In dev, add `process.on('SIGTERM')` cleanup so restarts free the port.",
 ""),
("How do I handle a promise rejection I can't avoid?",
 "Attach .catch at the boundary where you can act — log with context, return a fallback, and never leave floating promises unhandled.",
 ""),
("How do I compare two objects in JS tests?",
 "Use assert.deepStrictEqual, not ===. For dates and unordered arrays, normalize first (sort, map to ISO) so failures are readable.",
 ""),
("How do I stream a large file download in Node?",
 "Pipe response.body through fs.createWriteStream with backpressure; never await response.text() on gigabyte payloads.",
 ""),
("How do I parse CLI flags without dependencies?",
 "Walk process.argv, match --key value pairs, require the mandatory ones, and exit(2) with a usage line on error. Reach for a library past ~5 flags.",
 ""),
("How do I make fetch retry once on 5xx?",
 "Loop twice, retry only on 500-599 or network errors, break on 4xx. Add a 1s sleep before the retry and cap total attempts.",
 ""),
("How do I find which dependency pulls in a package?",
 "`npm ls <name>` prints the chain. For duplicates, `npm dedupe` or an overrides entry flattens them.",
 ""),
("How do I run a script only when files change?",
 "Use `node --watch` for dev reloads, or a file watcher that debounces events — editors save in bursts that trigger duplicate runs.",
 ""),
("How do I fix CORS errors during local dev?",
 "CORS is enforced by the browser, not your code. Proxy the API through your dev server or set Access-Control-Allow-Origin on the backend.",
 "fetch('http://api:8000/x') blocked"),
("How do I store secrets for a Node app?",
 "Read from environment variables, never commit .env. Fail fast at startup listing which vars are missing.",
 "API_KEY=... node app.js"),
("How do I log structured output in Node?",
 "Emit one JSON object per line with level, msg, and a request id. Plain text logs can't be filtered once volume grows.",
 ""),
("How do I gracefully shut down an HTTP server?",
 "On SIGTERM: stop accepting, await in-flight requests with a deadline, then close DB pools. Kill -9 is for hangs, not routine deploys.",
 ""),
("How do I test an async function that times out?",
 "Await it with assert.rejects and a test-level timeout slightly above the function deadline. Flaky timing means the test needs fake timers.",
 ""),
("How do I diff two JSON files quickly?",
 "Normalize with `jq -S .` on both, then plain diff. Key order and whitespace noise disappear.",
 "diff <(jq -S . a.json) <(jq -S . b.json)"),
("How do I extract one field from JSON on the CLI?",
 "`jq -r '.items[].name' data.json`. Explore shape first with bare `jq .`, then narrow the filter.",
 ""),
("How do I check my public IP from the terminal?",
 "`curl -s ifconfig.me`. For DNS debugging use `dig +short`, not ping.",
 ""),
("How do I count lines of code excluding blanks?",
 "`grep -v '^\\s*$' src/*.py | wc -l`. For real stats install tokei — one command, per-language breakdown.",
 ""),
("How do I find the largest files under a directory?",
 "`find . -type f -exec du -h {} + | sort -rh | head`. Add `-xdev` to stay on one filesystem.",
 ""),
("How do I watch a log file live with filtering?",
 "`tail -F app.log | grep --line-buffered ERROR`. -F survives rotation; --line-buffered keeps output realtime through the pipe.",
 ""),
("How do I rerun the last command with sudo?",
 "`sudo !!` re-executes the previous line as root. Check what it was first with `history 1` if you're unsure.",
 ""),
("How do I background a running foreground process?",
 "Ctrl+Z suspends, then `bg` resumes in background; `disown` detaches it from the shell so logout won't kill it.",
 ""),
("How do I transfer a file between two servers?",
 "`scp file user@host:/path` for one-offs, rsync for repeats. Verify checksums on anything irreplaceable.",
 ""),
("How do I check disk space and the biggest hogs?",
 "`df -h` for partitions, then `du -sh * | sort -h` inside the full one. Clear caches before touching data.",
 ""),
("How do I see which process eats my RAM?",
 "`ps aux --sort=-%mem | head`. For live view use htop; look at RES, not VIRT.",
 ""),
("How do I kill all processes matching a name?",
 "`pkill -f 'pattern'` — quote the pattern and run `pgrep -f 'pattern'` first to preview victims.",
 ""),
("How do I run a command at a schedule?",
 "Add a cron line `0 2 * * * /path/backup.sh >>/var/log/b.log 2>&1`. Test the script manually first; cron's PATH is minimal.",
 ""),
("How do I keep a command running after logout?",
 "Launch inside tmux, or `nohup cmd &` for fire-and-forget. Tmux wins whenever you may need to reattach.",
 ""),
("How do I compare two directories?",
 "`diff -rq dir1 dir2` lists differing files; rsync -avn shows what would sync. Both beat eyeballing.",
 ""),
("How do I create a Python venv and install deps?",
 "`python -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt`. Never pip install into system python.",
 ""),
("How do I freeze exact dependency versions?",
 "`pip freeze > requirements.txt` after verifying things work. For apps pin everything; for libraries pin ranges.",
 ""),
("How do I speed up Docker builds?",
 "Order Dockerfile steps from least to most changing, copy dependency files first, and enable BuildKit cache mounts for package managers.",
 ""),
("How do I inspect why a container exits?",
 "`docker logs <name>` first, then `docker inspect <name> --format='{{.State.ExitCode}}'`. Reproduce with an interactive shell override.",
 ""),
("How do I clean up Docker disk usage?",
 "`docker system df` shows the hogs; `docker system prune -a --volumes` reclaims. Run df before and after to confirm.",
 ""),
("How do I forward a local port over SSH?",
 "`ssh -L 8080:localhost:80 user@host` maps remote 80 to local 8080. Add -N -f to run it in the background.",
 ""),
("How do I generate an SSH key pair safely?",
 "`ssh-keygen -t ed25519 -C 'me@host'`, empty passphrase only for automation accounts, and `chmod 600` the private key.",
 ""),
("How do I test an API endpoint quickly?",
 "`curl -s -w '\\n%{http_code}\\n' URL` shows body plus status. For JSON APIs pipe through jq to stay sane.",
 ""),
("How do I handle expired TLS certificates locally?",
 "Check expiry with `openssl s_client -connect host:443 | openssl x509 -dates`, renew via your ACME client, then reload — not restart — the service.",
 ""),
("How do I merge two dictionaries in Python 3.9+?",
 "`a | b` returns a new dict with b winning conflicts; `a |= b` updates in place. Both leave the inputs readable.",
 "a={'x':1}\nb={'y':2}"),
("How do I chunk a list into fixed-size pieces?",
 "`[lst[i:i+n] for i in range(0, len(lst), n)]`. The last chunk is shorter — handle it instead of assuming full size.",
 ""),
("How do I deduplicate while preserving order?",
 "`list(dict.fromkeys(items))`. Only works for hashables; for dicts, key on one field like row['id'].",
 ""),
("How do I run a one-off Python snippet without a file?",
 "Use `python -c \"print('hi')\"` for throwaways. Anything you run twice deserves a real script under version control.",
 ""),
("How do I pretty-print JSON in the terminal?",
 "Pipe through `python -m json.tool`, or jq for color. Never eyeball minified blobs — formatting first saves misreads.",
 ""),
]
for q, a, inp in P06:
    add(6, "code-en", q, a, inp)

# ================= part-07: terminal x63 =================
P07 = [
("Termux 里 node 版本太低装不上依赖怎么办",
 "用 pkg 升级 node 到 >=18，别用旧源残留。node -v 确认后删 node_modules 重 npm ci，慢就换 npmmirror 镜像。",
 ""),
("tmux 断开后怎么找回会话",
 "tmux attach 找回，tmux ls 列出全部。跑长任务前 tmux new -s work 起名，断网重连也不丢。",
 ""),
("管道给 CLI 传输入没反应怎么查",
 "先确认上游有输出（加 head 验证），再确认接收端读到 end 事件才处理。空输入直接提示用法退出 2。",
 "echo hi | mini-code -p 总结 -q"),
("git 只看状态的最短命令",
 "git status -sb，一行看分支加改动。mini-code 里直接 /git status -sb。",
 ""),
("grep 结果混进 node_modules 怎么排除",
 "mini-code 的 grep 默认排除 node_modules/.git/dist；手写加 --exclude-dir=node_modules。",
 ""),
("run_command 卡住不动怎么办",
 "先加小超时（如 10 秒）试探，长任务拆步跑，输出只看前几十行定位死锁点。",
 ""),
("手机上怎么让服务一直跑",
 "tmux 里跑，退出用 detach 不杀进程；再拿 Termux wakelock 防休眠杀后台。",
 ""),
("Ollama 接 mini-code 怎么配",
 "export OPENAI_BASE_URL=http://localhost:11434/v1，模型名填 ollama 已 pull 的。",
 ""),
("npm ci 和 install 用哪个",
 "复现环境用 npm ci（按锁文件干净装）；加包才用 install。提交前跑 npm run check。",
 ""),
("输出被截断只显示前一部分怎么办",
 "看到截断提示就缩小范围：grep 定行号，read_file 分段看，别整盘读。",
 ""),
("怎么同时看分支和改动概览",
 "git branch --show-current 看分支，git diff --stat 看改动，一屏够用。",
 ""),
("写文件被越界/敏感路径拒绝怎么办",
 "只能写 cwd 内相对路径，.env/.ssh/credentials 默认拒绝。换路径或改文件名重试。",
 ""),
("Ctrl+C 直接退出了是为什么",
 "空闲按 Ctrl+C 是退出，运行中按才是中止。会话文件还在，重进即可继续。",
 ""),
("怎么清空对话重新开始",
 "/clear 清空显示，/undo 撤回上一轮。文件改动不受影响，要全新会话直接重启。",
 ""),
("shell 提示找不到 mini-code",
 "没 npm link 就只能 node src/index.js；link 后检查 PATH 是否含 npm 全局 bin。",
 ""),
("怎么给长命令加超时",
 "run_command 传 timeout_ms（如 10000），超时会被终止。先拆小步再放开超时。",
 ""),
("git log 刷屏怎么办",
 "加 --oneline -10 只看最近十条，要细节再 git show 单条跟进。",
 ""),
("tmux 多会话来回切快捷键",
 "Ctrl+b s 选会话，Ctrl+b d  detach。建会话时 -s 起名好找。",
 ""),
("手机存储不足 npm 报错怎么办",
 "npm cache clean --force，清旧包后删 node_modules 重装。大文件别进仓库。",
 ""),
("怎么确认 npm 镜像生效",
 "npm config get registry 看地址，装个小包测速度，失败切回官方源排除法。",
 ""),
("管道中文乱码怎么查",
 "两端统一 UTF-8：locale 看 LANG，file 确认文件编码，iconv 转码再进管道。",
 ""),
("怎么看端口被谁占了",
 "ss -lntp 或 lsof -i :端口，看 PID 再 kill 或换端口。先看再杀。",
 ""),
("磁盘满了先查哪里",
 "df -h 看哪个分区满，du -sh * 找大户。先清缓存旧日志，再动数据。",
 ""),
("怎么找大于 100M 的文件",
 "find . -size +100M -exec ls -lh {} \\;，列出来逐个确认再删。",
 ""),
("批量把 txt 改成 md 怎么做",
 "for f in *.txt; do mv \"$f\" \"${f%.txt}.md\"; done，先把 mv 换 echo 预演一遍。",
 ""),
("每天自动备份目录怎么做",
 "cron 加 tar -czf 带日期的包，只留最近 7 份。备份不演练恢复等于没备。",
 ""),
("日志只看报错前后 5 行怎么做",
 "grep -n -C5 ERROR app.log，先定位行号再看上下文，别全文件翻。",
 ""),
("进程死了怎么自动拉起",
 "systemd 或循环脚本拉起，拉起前写日志。连续失败要告警，别无限空转。",
 ""),
("环境变量改完不生效怎么查",
 "export 只对当前 shell 有效，写入 ~/.bashrc 并 source，脚本里用 env 确认值。",
 ""),
("软链断了怎么查",
 "find . -xtype l 找断链，ls -l 看指向，ln -sf 重建。",
 ""),
("解压前不知道格式怎么办",
 "file 先看类型再选 tar/unzip，解到空目录，防 tar 炸弹覆盖文件。",
 ""),
("ssh 每次输密码怎么办",
 "ssh-copy-id 传公钥，私钥 chmod 600。跳板机用 ProxyJump，别到处散私钥。",
 ""),
("curl 只看状态码怎么做",
 "curl -s -o /dev/null -w '%{http_code}' URL，先通再看响应体。",
 ""),
("jq 取 JSON 字段怎么做",
 "先裸 jq . 看结构，再 jq -r '.data.list[].name' 取值。-r 去引号好管道。",
 ""),
("sed 批量替换怎么做才安全",
 "先不加 -i 预览输出，确认再 -i.bak 备份改，留一份可回滚。",
 ""),
("awk 取第二列怎么做",
 "awk '{print $2}'，分隔符特殊用 -F':' 指定，表头先 NR==1 跳过看清列。",
 ""),
("xargs 并行跑任务怎么做",
 "find . -name '*.log' | xargs -P4 -I{} gzip {}，先拿 3 个文件试再全量。",
 ""),
("两台机器同步目录怎么做",
 "rsync -avz 先加 -n dry-run 看方向，确认再真跑。--delete 会删文件，慎用。",
 ""),
("chmod 改错了怎么救",
 "先停手别递归乱改，用备份或 git 恢复权限。目录 755 文件 644 起步。",
 ""),
("history 里找上次命令怎么做",
 "history | grep 关键字，或 Ctrl+r 反向搜。找到先核对再回车，别盲跑。",
 ""),
("常用长命令怎么省 keystrokes",
 "alias 写进 .bashrc，如 alias gs='git status -sb'。脚本里用全称保可读。",
 ""),
("怎么看命令到底执行了什么",
 "bash -x script.sh 跟踪展开，或命令前加 echo 预演。删改操作必预演。",
 ""),
("scp 传大文件中断怎么办",
 "换 rsync --partial --progress，可断点续传。中断先看对端已有大小再续。",
 ""),
("怎么看系统负载和瓶颈",
 "uptime 看 load，top/htop 看 CPU 内存，iowait 高先查磁盘。",
 ""),
("swap 用满了怎么办",
 "free -h 确认，找内存大户重启或加内存。swap 只是止痛，不是解法。",
 ""),
("怎么定时清旧日志",
 "find logs -mtime +30 -delete 之前先 -ls 预览，cron 每天跑一次。",
 ""),
("docker 容器起不来先查什么",
 "docker logs 看退出原因，再 inspect 看挂载端口，最后 docker run --rm -it 进镜像复现。",
 ""),
("怎么进运行中容器排查",
 "docker exec -it <name> sh，没 sh 用 bash。只读排查别顺手改容器内文件。",
 ""),
("apt update 失败怎么办",
 "先看报错是网络还是源：换源/检查代理，apt clean 后重试。锁文件被占就等进程结束。",
 ""),
("git 误删分支怎么恢复",
 "git reflog 找分支最后 commit，git branch <name> <sha> 重建。推送过的去远端找也行。",
 ""),
("merge 冲突了标准流程是什么",
 "git status 看冲突文件，逐个修完 git add，最后 git commit 收尾。别 --hard，除非你确定。",
 ""),
("想暂存手头工作切分支怎么做",
 "git stash push -m 说明，切回来 git stash pop。长期放 stash 会忘，尽快落盘。",
 ""),
("怎么看某行代码是谁改的",
 "git blame -L 起止行 文件，一眼到人。再 git show 那次提交看上下文。",
 ""),
("公钥登不上先查哪三处",
 "sshd 开没开、authorized_keys 权限 600、公钥内容是否完整一行。三处全对才能进。",
 ""),
("cron 不执行怎么排查",
 "先确认 cron 服务在跑，再看日志 /var/log/cron，脚本用绝对路径，环境变量脚本内重设。",
 ""),
("curl 调 https 证书报错怎么办",
 "curl -v 看是哪段证书链，先确认系统时间对不对，再 --cacert 指定 CA。-k 只临时调试用。",
 ""),
("jq 处理超大 JSON 卡住怎么办",
 "换 jq --stream 流式处理，或 python -ijson 边读边过。别 cat 全读进内存。",
 ""),
("怎么对比两个目录差异",
 "diff -rq dir1 dir2 列出不同文件，要同步用 rsync -avn 预演。别肉眼对。",
 ""),
("nohup 和 tmux 怎么选",
 "要回来看输出、多次交互选 tmux；一次性后台跑完选 nohup。长期服务用 systemd。",
 ""),
("怎么给脚本加锁防重复跑",
 "flock -n 锁文件，拿不到锁直接退出。cron 每分钟任务必备。",
 ""),
("tar 解包到指定目录怎么做",
 "tar -xzf 包 -C 目标目录，目标先 mkdir -p。先 tar -tzf 列内容防路径穿越。",
 ""),
("怎么看文件编码",
 "file 文件名看个大概，enca/chardet 精确些。乱码先确认编码再转，别反复保存。",
 ""),
("怎么看命令的完整路径和别名",
 "type 看是别名函数还是文件，which 看路径。被 alias 遮住的真身用 command 前缀执行。",
 ""),
]
for q, a, inp in P07:
    add(7, "terminal", q, a, inp)

# ================= part-08: code-en x62 =================
P08 = [
("How do I round a float to 2 decimals in Python?",
 "Use f'{x:.2f}' for display, round(x, 2) for values. Floats are binary — money math belongs in Decimal.",
 ""),
("How do I flatten one level of nesting in Python?",
 "`[x for sub in rows for x in sub]`. One level only; deeper nesting wants an explicit recursive helper.",
 ""),
("How do I count items by category in Python?",
 "`collections.Counter(r['kind'] for r in rows)`. Then .most_common(5) for the top five.",
 ""),
("How do I zip two lists into a dict?",
 "`dict(zip(keys, vals))` stops at the shorter list. Assert equal lengths first when mismatch is a bug.",
 ""),
("How do I shuffle reproducibly in Python?",
 "`random.Random(42).shuffle(lst)` — a local instance avoids disturbing global random state used elsewhere.",
 ""),
("How do I time a code block in Python?",
 "Bracket with time.perf_counter() and subtract. perf_counter is monotonic; time.time can jump backwards.",
 ""),
("How do I profile the slowest function?",
 "Run `python -m cProfile -s cumulative script.py` and fix the top row. Guessing hotspots wastes the whole exercise.",
 ""),
("How do I stream a large download without RAM blowup?",
 "`requests.get(url, stream=True)` plus iter_content(8192) to disk. Never touch .content on huge files.",
 ""),
("How do I compare JSON ignoring key order?",
 "Load both and compare dicts — == ignores order by definition. Normalize with jq -S first for CLI diffs.",
 "a='{\"x\":1,\"y\":2}'"),
("How do I check path existence in Python?",
 "pathlib.Path('f').exists() for any entry, .is_file() to exclude directories. Good for preflight checks, not for TOCTOU races.",
 ""),
("How do I exit a Node CLI with the right code?",
 "Write errors to stderr, process.exit(1) for failures, exit(2) for usage errors. Zero is reserved for real success.",
 ""),
("How do I watch files reliably in Node?",
 "fs.watchFile polls (reliable, slow); fs.watch is instant but platform-quirky. Either way debounce — editors fire save bursts.",
 ""),
("How do I cap JSON body size in a server?",
 "Count bytes as chunks arrive and abort past the limit (say 1MB) with 413. Unbounded parsing is a DoS invitation.",
 ""),
("How do I sanitize untrusted text for terminal display?",
 "Strip ANSI/OSC escapes before printing — same idea as mini-code's sanitize. Otherwise output can hijack the clipboard.",
 ""),
("How do I retry fetch only on server errors?",
 "Retry 5xx and network failures once after a short sleep; break immediately on 4xx since retrying won't help.",
 ""),
("How do I find who depends on a package?",
 "`npm ls <name>` prints the dependency chain. Flatten duplicates with dedupe or an overrides entry.",
 ""),
("How do I reload code on file change in dev?",
 "`node --watch app.js` restarts on saves. For tests use the runner's watch mode instead of nodemon soup.",
 ""),
("Why am I getting CORS errors locally?",
 "The browser blocks cross-origin reads, not your code. Proxy /api through the dev server or set Allow-Origin on the backend.",
 "fetch('http://api:8000/x') blocked"),
("Where do I put secrets in a Node app?",
 "Environment variables, validated at startup with a loud list of what's missing. .env files never get committed.",
 "API_KEY=... node app.js"),
("How do I write logs that stay searchable?",
 "One JSON object per line: level, msg, request id. Free-form printf logs become ungreppable at volume.",
 ""),
("How do I shut down an HTTP server cleanly?",
 "On SIGTERM stop accepting, drain in-flight requests against a deadline, then close pools. Save kill -9 for real hangs.",
 ""),
("How do I test a function that must time out?",
 "Use assert.rejects with a test timeout just above the deadline. If timing flakes, switch the test to fake timers.",
 ""),
("How do I exit a Python script with an error message?",
 "`raise SystemExit('reason')` or sys.exit(1) after printing to stderr. Plain return in main silently reports success.",
 ""),
("How do I make a dataclass with defaults in Python?",
 "@dataclass with field(default_factory=list) for mutable defaults. Bare [] as a default shares one list across instances.",
 ""),
("How do I run CPU-bound work around the GIL?",
 "multiprocessing for real parallelism, threads only for IO waiting. Measure first — spawning processes has its own cost.",
 ""),
("How do I cancel an asyncio task after N seconds?",
 "Wrap with asyncio.wait_for(coro, timeout=N) and catch TimeoutError. Long tasks should also checkpoint cancellation themselves.",
 ""),
("How do I read env vars with defaults in Python?",
 "`os.environ.get('PORT', '8080')`, cast to int explicitly. Crash loudly on required-but-missing vars at startup.",
 ""),
("How do I write a generator that cleans up?",
 "Put teardown in finally inside the generator, or use contextlib.contextmanager. Callers breaking early still trigger it on .close().",
 ""),
("How do I compare floats safely?",
 "Use math.isclose(a, b, rel_tol=1e-9) instead of ==. Binary floats can't represent most decimals exactly.",
 ""),
("How do I remove an item from a list by value?",
 "lst.remove(x) deletes the first match and raises ValueError if absent. For all matches rebuild with a comprehension.",
 ""),
("How do I get the caller's function name for logging?",
 "inspect.stack()[1].function gives it, but it's slow — cache or pass explicit context in hot paths.",
 ""),
("How do I make JSON output deterministic?",
 "json.dumps(obj, sort_keys=True, separators=(',', ':')). Deterministic bytes make caching and diffing reliable.",
 ""),
("How do I handle timezone-aware datetimes?",
 "Store UTC (datetime.now(timezone.utc)), convert to local only for display. Naive datetimes cause the classic off-by-hours bug.",
 ""),
("How do I split a string on multiple delimiters?",
 "re.split(r'[;,\\s]+', s) in one pass. Chained str.split calls leave empty tokens you'll then have to filter.",
 ""),
("How do I check a string starts with any of several prefixes?",
 "str.startswith(('http://', 'https://')) accepts a tuple. Faster and clearer than a regex for fixed prefixes.",
 ""),
("How do I remove whitespace-only lines from a file?",
 "Keep `line for line in f if line.strip()`. Deciding per-line beats regexing the whole blob.",
 ""),
("How do I transpose rows and columns?",
 "zip(*rows) transposes; wrap each tuple in list() if you need mutability. All rows must share a length.",
 ""),
("How do I find the index of the max element?",
 "max(range(len(xs)), key=lambda i: xs[i]). max() alone returns the value, not where it lives.",
 ""),
("How do I group items by a key function?",
 "itertools.groupby(sorted(rows, key=f), f) — note the sort is mandatory, groupby only groups runs.",
 ""),
("How do I consume an iterator in fixed batches?",
 "Take islice(it, n) repeatedly until empty. Materializing the whole stream first defeats the purpose.",
 ""),
("How do I memoize a recursive function?",
 "@functools.lru_cache on pure functions with hashable args. Unhashable args need an explicit dict keyed by repr.",
 "fib(100) hangs"),
("How do I run a subprocess with a timeout?",
 "subprocess.run(cmd, timeout=30) raises TimeoutExpired — catch it and kill explicitly, or the child keeps running.",
 ""),
("How do I parse CLI args robustly in Python?",
 "argparse with required=True on mandatory flags and a clear epilog example. Hand-rolled sys.argv parsing rots past three flags.",
 ""),
("How do I write atomic files that never half-exist?",
 "Write to temp + os.replace() onto the target. Readers either see the old file or the new one, never a mix.",
 ""),
("How do I lock a file against concurrent writers?",
 "fcntl.flock in a with-block around the critical section. Locks release on close — including crash-close, which is the point.",
 ""),
("How do I tail the last N lines efficiently?",
 "collections.deque(f, maxlen=N) streams without loading the file. readlines()[-N:] works but reads everything.",
 ""),
("How do I detect file encoding before reading?",
 "Try utf-8 first, fall back to chardet only on failure. Declaring 'latin-1' up front silently mojibakes real UTF-8.",
 ""),
("How do I walk a tree skipping hidden dirs?",
 "os.walk with in-place `dirs[:] = [d for d in dirs if not d.startswith('.')]` — mutating dirs prunes the descent.",
 ""),
("How do I compute a file hash without loading it?",
 "Read in 64KB chunks into hashlib.sha256(). One pass, constant memory, works on multi-GB files.",
 ""),
("How do I serialize datetime to JSON?",
 "Default=str drops fidelity; better a custom default=lambda o: o.isoformat(). Parse back with fromisoformat.",
 ""),
("How do I deepcopy only one nested branch?",
 "copy.deepcopy(node['branch']) copies just that subtree. Whole-structure deepcopy on huge graphs wastes time and RAM.",
 ""),
("How do I throttle API calls to N per second?",
 "Track last-call timestamps and sleep the deficit before each call. Token-bucket libraries earn their keep past trivial cases.",
 ""),
("How do I add jitter to retries?",
 "sleep(base * 2**attempt + random.uniform(0, 1)). Without jitter every client retries in lockstep and re-hammers the server.",
 ""),
("How do I structure a long script so it's testable?",
 "Move logic into functions taking explicit args, guard side effects under `if __name__ == '__main__'`. Importable beats executable.",
 ""),
("How do I fail fast on unset variables in bash?",
 "`set -u` turns unset expansion into an error. Pair with ${VAR:?message} at the top for a clear complaint.",
 ""),
("How do I make a bash script exit on first failure?",
 "`set -euo pipefail` at line one. Then handle expected failures explicitly with `|| true` so they stay visible.",
 ""),
("How do I iterate over filenames with spaces in bash?",
 "`find . -print0 | while IFS= read -r -d '' f`. Plain for-loops word-split on spaces and break.",
 ""),
("How do I check if a command exists in a script?",
 "`command -v jq >/dev/null || { echo 'need jq'; exit 1; }`. which is unportable and noisy.",
 ""),
("How do I redirect both stdout and stderr to a file?",
 "`cmd >out.log 2>&1` — order matters, 2>&1 must come last. For tee-style dual output pipe through `| tee`.",
 ""),
("How do I run the previous command's output as a command?",
 "Don't — capture intentionally with $(...) instead. Blindly evaling last output is how accidents happen.",
 ""),
("How do I sort by the second CSV column numerically?",
 "`sort -t, -k2 -n file.csv`. Without -n, 10 sorts before 9 and your ranking is wrong.",
 ""),
("How do I deduplicate a sorted file keeping one copy?",
 "`sort -u file` or `uniq file`. uniq only collapses adjacent lines, so sort first when input is unordered.",
 ""),
]
for q, a, inp in P08:
    add(8, "code-en", q, a, inp)

# ================= part-09: terminal x62 =================
P09 = [
("git 误删已推送的分支怎么恢复",
 "reflog 找 commit 重建本地分支，再 git push origin 重建远端。远端垃圾回收前都在，尽快动手。",
 ""),
("merge 冲突标准流程是什么",
 "git status 看冲突文件，逐个修完 git add，最后 commit 收尾。没把握别 --hard。",
 ""),
("stash 存了东西忘了怎么办",
 "git stash push -m 说明，切回来 pop。stash 别放过夜，尽快落盘成提交。",
 ""),
("查出肇事提交后下一步做什么",
 "git blame -L 起止行 文件定位人，再 git show 那次提交看上下文。",
 ""),
("ssh 加 -v 看卡在哪一步",
 "sshd 在跑、authorized_keys 600、一行完整公钥。三处全对才能进。",
 ""),
("cron 里中文乱码/命令找不到怎么办",
 "确认 cron 服务在，再看 /var/log/cron。脚本用绝对路径，环境变量脚本内重设。",
 ""),
("curl 报证书错误怎么办",
 "curl -v 看证书链，先对系统时间，再 --cacert 指定 CA。-k 只临时调试用。",
 ""),
("jq 内存爆了有什么替代",
 "换 jq --stream 流式，或 python 边读边过。别 cat 全读进内存。",
 ""),
("systemd 和 tmux 跑服务怎么选",
 "要回看输出、多轮交互选 tmux；一次跑完选 nohup。长期服务用 systemd。",
 ""),
("flock 锁没释放怎么办",
 "flock -n 锁文件拿锁，拿不到直接退出。每分钟跑的 cron 任务必备。",
 ""),
("tar 包里有绝对路径怎么办",
 "tar -xzf 包 -C 目标目录，目标先 mkdir -p。先 -tzf 列内容防路径穿越。",
 ""),
("怎么看文件编码再转码",
 "file 先看个大概再 iconv -f 从 -t 到。转前备份，乱码确认编码再动手。",
 ""),
("scp 大文件中断怎么办",
 "换 rsync --partial --progress 断点续传。先看对端已有大小再续传。",
 ""),
("怎么看系统瓶颈在哪",
 "uptime 看 load，top 看 CPU 内存，iowait 高先查磁盘而不是加内存。",
 ""),
("怎么看是谁吃掉了内存",
 "free -h 确认后找内存大户，重启泄漏进程或加内存。swap 是止痛不是解法。",
 ""),
("怎么定时清 30 天前日志",
 "find logs -mtime +30 先 -ls 预览，确认再 -delete，放进 cron 每天跑。",
 ""),
("容器里没有 shell 怎么排查",
 "docker exec -it <name> sh，只读排查。别顺手改容器内文件，改了也随容器丢。",
 ""),
("apt 被锁住怎么办",
 "看报错分网络还是源：换源或查代理，apt clean 后重试。锁被占就等进程结束。",
 ""),
("两块盘怎么看各剩多少",
 "df -hT 连类型一起看，挂载点对不上先 mount | grep 确认再扩容。",
 ""),
("怎么看谁在吃带宽",
 "iftop 或 nethogs 按进程看，云上先看费用告警再抓包，别上来就 tcpdump。",
 ""),
("ssh 断线后命令停了怎么办",
 "事前 tmux，事后只能重跑。关键任务加 nohup 或写成可重入脚本。",
 ""),
("怎么批量杀一类进程",
 "先 pgrep -f 看名单，确认再 pkill -f。名单里有无辜进程就逐个 kill。",
 ""),
("history 不记录了怎么查",
 "看 HISTFILE 指向、磁盘满没满、是不是多 shell 覆盖写。重要命令顺手记文档。",
 ""),
("新机器装机必跑哪几步",
 "换源、装 git/tmux/vim、配 ssh、拉 dotfiles。每步跑通再下一步，别一键脚本梭哈。",
 ""),
("怎么验证备份真能恢复",
 "定期拿一份恢复到空目录跑通。没演练过的备份等于没有。",
 ""),
("rm 删错了还有救吗",
 "ext4 基本没救，xfs 更没救。事前 alias rm='rm -i'、重要目录快照，事后只能翻备份。",
 "rm -rf /tmp/work"),
("find 删文件怎么先预演",
 "先不加 -delete 跑一遍看名单，确认再加。-name 模式先用 -ls 输出核对。",
 "find . -name '*.tmp'"),
("ln 硬链和软链怎么选",
 "跨分区、指目录用软链；同分区防误删用硬链。ln -s 目标 链接名别写反。",
 ""),
("df 和 du 对不上怎么办",
 "删掉但被进程占着的文件：lsof | grep deleted 找到重启进程，空间立刻回来。",
 ""),
("怎么看文件被哪个进程占用",
 "lsof 文件名或 fuser -v，umount 提示 busy 时就用它找元凶。",
 ""),
("内核日志报错去哪看",
 "dmesg | tail，OOM、磁盘错都在这。云机器配串口日志留底。",
 ""),
("服务开机自启怎么做",
 "systemctl enable 服务名，enable 后 reboot 验证一次。只 start 不 enable 重启就没。",
 ""),
("怎么看服务为什么启动失败",
 "systemctl status 看最后一屏，再 journalctl -u 服务名 -e 看完整日志。",
 ""),
("journal 日志把盘写满怎么办",
 "journalctl --vacuum-size=500M 立刻瘦身，/etc/systemd/journald.conf 限额防再犯。",
 ""),
("怎么给普通用户 sudo 免密",
 "visudo 加 NOPASSWD，只给具体命令。ALL 免密等于没密码，想清楚再给。",
 ""),
("ssh 端口被扫爆了怎么办",
 "改端口+fail2ban 限频，公钥登录关密码。别只改端口，扫描器全端口扫。",
 ""),
("怎么看登录失败记录",
 "journalctl _COMM=sshd | grep Failed，或 lastb 看坏登录。配告警别天天人肉看。",
 ""),
("证书还有几天过期怎么查",
 "openssl s_client -connect 域名:443 | openssl x509 -noout -dates，剩 30 天就续。",
 ""),
("nginx 改完配置怎么热加载",
 "nginx -t 先测语法，通过再 nginx -s reload。直接 restart 会断连接。",
 ""),
("怎么抓 http 明文看问题",
 "curl -v 看握手和头，tcpdump 只抓包头。生产抓包先脱敏再存文件。",
 ""),
("DNS 不生效先查哪",
 "getent hosts 看解析结果，再看 /etc/resolv.conf 和缓存。改 hosts 立刻生效好验证。",
 ""),
("ping 通但 curl 不通怎么查",
 "ping 走 ICMP，curl 走 TCP：telnet 端口看通不通，再查防火墙和代理变量。",
 ""),
("怎么看路由走哪",
 "traceroute 或 mtr 看路径，云上先查安全组，本地先查默认网关。",
 ""),
("网卡名变了怎么办",
 "ip link 看现名，netplan/网卡配置跟现名对齐。别硬背 eth0，新系统名不一样。",
 ""),
("scp 慢怎么提速",
 "换 rsync + 压缩 -z，跨国加 -e 'ssh -C'。先测带宽，加密算法一般不是瓶颈。",
 ""),
("两个文件不同但看不出差别怎么办",
 "diff <(cat -A a) <(cat -A b) 看不可见字符，八成是换行或尾空格。",
 ""),
("Windows 传来的脚本跑不动怎么办",
 "八成 CRLF：sed -i 's/\\r$//' 转 LF，再 chmod +x。先 file 确认。",
 "bash build.sh"),
("脚本在本机行、CI 不行怎么办",
 "对照环境：bash 版本、换行符、PATH、env。CI 首行加 set -x 打展开日志。",
 ""),
("make 报 missing separator 怎么办",
 "配方行必须 Tab 开头，空格不行。cat -A 看到 ^I 才是 Tab，重写那一行。",
 ""),
("gcc 找不到头文件怎么办",
 "apt-file 或 -dev 包名补头文件，-I 指定路径。先看报错到底缺哪个 .h。",
 ""),
("python 编译扩展缺 Python.h 怎么办",
 "装 python3-dev，再 pip install。venv 里装也一样要系统头文件。",
 ""),
("pip 源超时怎么办",
 "pip config 换国内源，或 pip -i 单次指定。公司网先查代理变量。",
 ""),
("npm 装包卡在 idealTree 怎么办",
 "删 package-lock 重装是下策，先清缓存 npm cache clean --force，再看是不是 registry 抽风。",
 ""),
("git clone 大仓库太慢怎么办",
 "--depth 1 浅克隆，或 --filter=blob:none 按需取。历史真要再 git fetch --unshallow。",
 ""),
("git push 被拒绝非快进怎么办",
 "git pull --rebase 同步再推，冲突修完 continue。别 --force 推公共分支。",
 ""),
("想撤回上次提交但保留改动怎么做",
 "git reset --soft HEAD~1，改动回暂存区。已 push 的用 revert，别 reset 公共历史。",
 ""),
("怎么只提交部分改动",
 "git add -p 逐块挑， unrelated 改动分两次提交。一坨提交 review 的人想打人。",
 ""),
("子模块更新不动怎么办",
 "git submodule update --init --recursive，URL 变了先 sync。能不用子模块就别用。",
 ""),
("tag 打错了怎么改",
 "本地删了重打，推过的用 git push --delete origin tag 再重推。CI 已跑的版本别改 tag。",
 ""),
("git 大文件推不上去怎么办",
 "git lfs track 大文件类型，或从历史里清掉。先看远端单文件限制，再决定 LFS 还是网盘。",
 ""),
("服务器时间不对怎么办",
 "timedatectl 看 NTP 状态，云机器打开时间同步。时间错了证书全挂，先对时再查别的。",
 ""),
("怎么看谁重启了机器",
 "last reboot 看重启记录，journalctl -b -1 看上次启动日志。云上再查控制台系统事件。",
 ""),
]
for q, a, inp in P09:
    add(9, "terminal", q, a, inp)

# ================= part-10: code-zh x40 + code-agent x22 =================
P10_ZH = [
("这段 Python 报 KeyError 怎么修", "键不存在。用 d.get('k') 给默认值，或先 if 'k' in d 再取。别拿 try 包大段代码。", "d={}\nprint(d['k'])"),
("循环里反复 open 怎么改快", "把 open 移出循环，或一次读入内存。IO 在循环里是头号慢源，先搬出来再谈别的。", "for i in range(n):\n  f(open(f))"),
("写一个读 CSV 按列求和的脚本", "csv.DictReader 逐行读，float 转失败跳过并计数，最后打印总数和坏行数。", "a,b\n1,2\nx,3"),
("这个 LIKE 前缀通配查询怎么优化", "EXPLAIN 先看走没走索引：'%x%' 走不了，改全文索引或前缀匹配，顺手把 SELECT * 缩成要的列。", "SELECT * FROM t WHERE name LIKE '%x%'"),
("帮我 review 这段删文件 diff", "意图先行再看边界：变量为空会删哪、通配符展开范围、有没有备份。rm 相关 diff 默认按危险品审。", "+rm -rf $dir"),
("怎么给 add 写单测", "正常、边界、异常各一例：1+2、0+0、字符串相加。用最小断言锁住行为，别测实现细节。", "def add(a,b): return a+b"),
("这个匹配 11 位数字的正则什么意思", "逐段拆：^ 行首、\\d 数字、{11} 十一个、$ 行尾。拿 10 位和 12 位反例验证。", r"^\d{11}$"),
("容器起不来先查什么", "docker logs 看退出原因，再 inspect 看挂载和端口映射，最后 --rm -it 进镜像复现。", ""),
("推导和循环到底选哪个", "纯转换用推导，一眼看完；带分支、异常、日志用循环。可读性优先于行数。", ""),
("JSON 解析失败怎么兜底", "try 抓 JSONDecodeError，给默认值并记原文前 100 字。坏输入只能污染一条，不许炸全程。", ""),
("浅拷贝踩坑了怎么理解", "浅拷只拷第一层，嵌套还是同一引用。改嵌套互相影响就换 deepcopy，或重构掉共享。", "b = a.copy()"),
("CPU 密集任务开多线程没用怎么办", "换 multiprocessing 真并行，线程只适合 IO 等待。先确认瓶颈真是 CPU 再换。", ""),
("这段拼接 SQL 怎么改才安全", "改参数化查询：cursor.execute(sql, (n,))。表名动态就走白名单，别拼。", "f\"select * where name='{n}'\""),
("OFFSET 翻页越来越慢怎么办", "改键集分页 WHERE id > 上页末位 LIMIT n。OFFSET 是跳过多少读多少，页越深越慢。", ""),
("报错信息太秃怎么加上下文", "raise 时带上关键 id 和输入摘要：f'pay failed id={id}'。日志同理，没 id 的报错等于没报。", ""),
("递归爆栈了怎么改", "改循环加显式栈；必须递归就分治缩小深度。先确认能不能迭代，能就别递归。", "RecursionError"),
("删日志文件前怎么确认安全", "ls 先看名单，确认只有 .log，再 git status 确认干净，最后删。通配符先 echo 展开看。", "rm *.log"),
("测试挂了代码看着没错先看什么", "看第一行报错和堆栈顶，写最小复现，最后 git stash 二分最近改动。别通读代码猜。", ""),
("线上出 bug 先干什么", "先止血：回滚、限流、摘流量。定位根因第二，复盘加单测第三。顺序错了越修越炸。", ""),
("重构第一步做什么最稳", "先给要动的函数补单测锁住行为，再小步改、频繁跑。一次只动一处，绿了再往下。", ""),
("字典 get 和 setdefault 分不清", "只读用 get('k', 默认)，累积用 setdefault('k', [])。后者会写入字典，别在只读处用。", ""),
("except 裸奔有什么坏处", "裸 except 连 KeyboardInterrupt 都吞，还掩盖 bug。只抓你预期的异常，末尾别跟万能 except。", "try:\n ...\nexcept:\n pass"),
("lambda 里循环变量全一样为什么", "闭包抓的是变量不是值：循环结束全指向末值。用默认参数 lambda x, i=i: ... 冻结当前值。", ""),
("pip 装包互相打架怎么办", "pip check 看冲突，venv 隔离项目，pip-tools 锁版本。系统 python 别装包。", "ERROR: conflict"),
("怎么判断该用缓存", "读多写少、结果可复算、能容忍过期，三条全中才加。缓存先定过期和淘汰，再写代码。", ""),
("接口超时重试几次合适", "读接口 3 次带退避，写接口先保证幂等再谈重试。无脑重试写接口会造出重复单。", ""),
("日志打太多把盘写满怎么办", "级别先调 info 起步，debug 按需开；加轮转和上限。日志是证据，不是作文。", ""),
("单测跑得慢怎么提速", "先 -x --lf 只跑失败，再并行 -n auto，最后把睡死的 time.sleep 换成 fake。", "pytest 10min"),
("类型注解到底值不值", "公共函数签名值得：调用方一眼看懂，mypy 提前抓错。内部三行小函数别折腾。", "def f(a, b):"),
("怎么给老代码加测试", "从 bug 修起：复现单测先红再绿，逐步包围核心路径。别立项重写测试体系。", ""),
("code review 被打回来怎么办", "先改事实问题（bug/边界），再谈品味分歧。一次只争一个点，别整单全驳回。", ""),
("魔法数字满天飞怎么治", "命名常量收拢：TIMEOUT=30。散在各处的 30 改一个漏一个， Review 见到就标。", "if x > 30: ..."),
("函数 200 行怎么拆", "按步骤提小函数，一屏一个，名字说清意图。拆完主流程像目录，细节各自成章。", ""),
("注释写什么不写什么", "写为什么不写是什么：hack 原因、坑的编号。代码能说清的别复读。", ""),
("异常该抛还是该返回", "跨层用异常，同层可预期用返回值。别用异常做正常分支，性能可读双输。", ""),
("性能优化第一步是什么", "先测：profile 找热点，优化第一行。凭感觉优化等于随机改代码。", ""),
("并发 bug 复现不了怎么办", "加日志和确定性种子，把并发压成串行复现。修完用压力循环验证，别跑一遍就收。", ""),
("上线前 checklist 都有啥", "单测绿、灰度、回滚方案、监控告警、数据备份。缺一个都别全量。", ""),
("技术债怎么跟业务谈", "翻译成风险和成本：不还，下次需求多几天。每次迭代带一小块，别攒大单。", ""),
("新人接手老项目先看什么", "README、依赖、启动命令、一条 happy path。跑起来再读代码，跑不起来读啥都没用。", ""),
]
for q, a, inp in P10_ZH:
    add(10, "code-zh", q, a, inp)
P10_AG = [
("用户让你重构，第一步做什么", "先读相关文件摸清现状，补最小单测锁行为，再 todo 列步小步改。没单测的重构是裸奔。", ""),
("测试挂了但代码看着没错怎么办", "读第一报错行，写最小复现，git stash 二分最近改动。三板斧下来基本定位。", ""),
("怎么确认删文件是安全的", "glob 看范围，git status 确认干净，先 mv 到 /tmp 放一天再真删。rm 没有后悔药。", ""),
("线上 bug 的处理顺序", "止血第一：回滚限流摘流量；定位第二；复盘加测第三。顺序反了就是次生事故。", ""),
("给这段代码写 commit message", "动词开头一句话：改了什么加为什么，如 fix(retry): 指数退避防惊群。 unrelated 别塞一单。", ""),
("探索陌生仓库从哪开始", "glob 看结构，grep 找入口（main/serve），read 读关键三文件。半小时画出调用链。", ""),
("多步任务怎么不跑偏", "todo_write 先列计划，做完一步勾一步。每偏一次回看清单，清单是方向盘。", ""),
("改前为什么要先读文件", "防改错：先看现状再 edit 精确替换，diff 预览按 y 确认。盲改等于盲焊。", ""),
("什么时候该停下来问用户", "需求模糊、删数据、长时间试错三处先问。问一句省两小时返工。", ""),
("上下文压缩后丢东西怎么办", "关键决定落盘 AGENTS.md/MEMORY.md，压缩只保最近加摘要。内存靠不住，文件靠得住。", ""),
("code review 重点看什么", "先看正确性边界并发安全，再看可读可测。风格分歧放最后，别拿格式挡 bug。", ""),
("并行任务怎么分工不打架", "按文件边界切分，接口先对齐，联调放 todo 里跟踪。共写一文件是冲突之源。", ""),
("估算工期总翻车怎么办", "拆到半天粒度，乘 1.5 报，留联调缓冲。估算不准多半是需求没拆细。", ""),
("需求中途大改怎么办", "冻结已做部分，改动单列 todo 重估。边改边做等于两份工期一份时间。", ""),
("文档和代码对不上听谁的", "听代码和报错，文档当线索。修完代码顺手把文档改了，别留第二个坑。", ""),
("生产事故复盘怎么写", "时间线、根因、止血动作、改进 todo。追责一句话带过，改进三条可落地。", ""),
("怎么判断任务做完了", "验收标准前置：单测绿、手动走一遍、文档更新。三条对勾才算完。", ""),
("技术选型怎么拍板", "列候选、定标准（成熟度/成本/团队熟悉度）、小步验证。拍板记录理由，半年后复看。", ""),
("线上配置改错了怎么办", "先回滚到上版，再diff 找差异。配置变更走 review，别 ssh 上去手改。", ""),
("怎么带新人熟悉终端助手", "先教三件套：read 先行、改前确认、跑完验证。再给 todo 习惯，第三天独立接小活。", ""),
("深夜被告警叫醒先干什么", "看告警原文和 dashboard，先止血限流，再叫人。困着修代码等于酒驾开车。", ""),
("复现不了的 bug 怎么跟进", "加日志、记现象、定下次观察点，todo 挂起别硬耗。放一放，线索会自己长出来。", ""),
]
for q, a, inp in P10_AG:
    add(10, "code-agent", q, a, inp)

# ================= part-11: zh x32 + en x30 =================
P11_ZH = [
("用一句话解释缓存", "缓存就是把算过的结果存起来，下次直接拿，代价是数据可能过期。先定过期时间再用。"),
("写个请假模板", "标题请假申请，正文三句：事由、时间、交接人。提前发，别卡着点发。"),
("给父母解释 fragmented 缓存", "跟冰箱剩菜一个道理：留着下顿热一下就能吃，但放久了会坏，要看保质期。"),
("分析年轻人存不下钱的原因", "主因是固定支出涨得比工资快，外加分期把未来透支了。先记一个月账，答案自己出来。"),
("给缓存功能写个更新公告", "本次新增查询缓存，列表页快一半。缓存 5 分钟，急着看最新点刷新。"),
("备份新手最容易踩的坑", "只备不恢复演练。真丢数据那天才发现备份是空的，每月恢复验证一次。"),
("索引一句话省时技巧", "条件列先加索引，查询从全表扫变直接定位，十万行以上效果立竿见影。"),
("怎么跟外行讲清复利", "利滚利：今年利息明年也生利息，时间越长差距越大，所以越早开始越值。"),
("用一句话解释拖延", "拖延是大脑在逃即时痛苦，不是懒。把任务切到 5 分钟能动手，阻力就没了。"),
("写个道歉模板", "三句：认错具体事、说补救、不找借口。别写小作文，对方要的是态度。"),
("给父母解释熬夜的危害", "熬夜等于让身体加夜班不给加班费，欠的觉周末补不回来，长期欠会集中报销。"),
("分析租房越租越远的原因", "市中心涨租快过涨薪，通勤时间换了居住面积。算上通勤，远未必便宜。"),
("给面试流程写个更新公告", "面试改两轮：首轮技术深聊，次轮业务实战。3 天内必给反馈，不让候选人干等。"),
("带团队新手最容易踩的坑", "自己上手最快，忍不住全自己干。团队成长慢，半年后你更累。先分能错的小活。"),
("写文档一句话省时技巧", "先写目录和结论，细节后补。没目录的文档写到一半就散，读者也找不到北。"),
("怎么跟外行讲清时间管理", "时间管理不是塞满，而是先保重要不紧急的事。每天先干那一件，再处理杂事。"),
("用一句话解释健康作息", "固定起床比固定睡觉更管用， biological clock 认的是起床光。先锁起床时间。"),
("写个感谢信模板", "具体谢哪件事、它帮了什么忙、以后怎么回报。三句，真诚比华丽管用。"),
("给父母解释理财定投", "每月固定买一点，不猜涨跌，靠时间熨平波动。投的是纪律，不是眼光。"),
("分析旅行计划总泡汤的原因", "计划按理想状态排，没留缓冲和备选。一个航班晚点，全盘崩。关键节点加 B 方案。"),
("给读书笔记写个更新公告", "笔记改卡片式：一条一卡，带出处和自己的话。方便以后拼文章，不再是大段抄。"),
("做饭备菜一句话省时技巧", "周末一次备好主食和肉分装，工作日只炒青菜。备菜一小时，换五天不点外卖。"),
("通勤新手最容易踩的坑", "只看地图时间，不看早晚高峰和换乘。签约前早晚各走一趟再决定。"),
("怎么跟外行讲清养猫开销", "猫本身不贵，贵的是医疗和意外。先备一年体检疫苗钱，再谈罐头自由。"),
("用一句话解释装修超预算", "超预算不是工人黑，是你边装边加项。开工前锁死清单，加一项就减一项。"),
("写个跳槽交接模板", "交接三件：进行中事项、账号权限、坑位记录。交接到能让接手人独立跑一周。"),
("给父母解释买车真成本", "车价只是首付，油、保险、保养、折价才是大头。一年先算两万养车钱再决定。"),
("分析熬夜刷手机停不下来的原因", "无限下滑没有结束信号，大脑停不下来。设个硬性停止：定时锁屏或看到闹钟就放下。"),
("给租房合同写个检查公告", "签前查五项：房东产权、押金退法、维修归谁、提前解约、水电怎么算。口头承诺写进去才算。"),
("面试紧张一句话技巧", "把面试当互相筛选，你也在面他们。心态一换，表达顺一半。准备三个反问问题压轴。"),
("带团队怎么开复盘会", "先摆事实时间线，再谈改进，每人一条可落地。追责的话一句带过，多了没人说真话。"),
("写文档给谁看决定怎么写", "给新人写步骤，给老人写变更。对象错了，写再细也没人看。开头先写读者是谁。"),
]
for ins, out in P11_ZH:
    add(11, "zh", ins, out)
P11_EN = [
("Explain caching simply in 3 sentences.",
 "Cache stores computed results for reuse. Reads get fast, but data can go stale. Always set an expiry before using one. (1/30)"),
("Write a polite email saying no about a deadline extension.",
 "Thank them, state the constraint plainly, offer an alternative date. Short and kind beats long and evasive. (2/30)"),
("What is the difference between retries and redundancy?",
 "Retries repeat the same call; redundancy runs spares in parallel. Use retries for transient blips, redundancy for hard failures. (3/30)"),
("How do I debug auth tokens failing silently?",
 "Decode the token to check expiry and audience first, then compare scopes against the endpoint. Most silent failures are expired or mis-scoped tokens. (4/30)"),
("Give a 5-item checklist for env config.",
 "Names documented, secrets out of repo, defaults safe, missing vars fail fast, staging mirrors prod keys. (5/30)"),
("Explain pagination simply in 3 sentences.",
 "Pagination splits big lists into pages. Keyset pages beat OFFSET on large tables. Always return a cursor for the next page. (6/30)"),
("Write a polite email saying no about a feature request.",
 "Acknowledge the need, explain the tradeoff, suggest the closest alternative. No with a reason keeps trust. (7/30)"),
("What is the difference between monitoring and alerting?",
 "Monitoring records what happens; alerting wakes someone when thresholds break. Alert only on actionable symptoms. (8/30)"),
("How do I debug webhooks that never arrive?",
 "Check the sender's delivery log first, then your firewall and signature verification. Nine times out of ten the receiver rejected the signature. (9/30)"),
("Give a 5-item checklist for onboarding.",
 "Laptop ready day one, buddy assigned, first small task week one, docs tour, feedback at day 30. (10/30)"),
("Explain rate limits simply in 3 sentences.",
 "Rate limits cap calls per window to protect the server. Clients should back off with jitter. Hitting 429 means slow down, not retry harder. (11/30)"),
("Write a polite email saying no about a meeting.",
 "Decline with the reason in one line and propose async instead. Protecting focus is legitimate. (12/30)"),
("What is the difference between backup and archive?",
 "Backups restore recent state fast; archives preserve old data cheaply. Test restores monthly or backups are fiction. (13/30)"),
("How do I debug time zone bugs?",
 "Store UTC everywhere, convert only at display. Reproduce with a fixed clock set to the reporter's zone. (14/30)"),
("Give a 5-item checklist for refactoring.",
 "Tests lock behavior, one area at a time, run suite often, no feature mixing, review the diff before merging. (15/30)"),
("Explain standup notes simply in 3 sentences.",
 "Standups sync blockers, not status theater. Three lines: done, next, blocked. Anything longer becomes a separate talk. (16/30)"),
("Write a polite email saying no about a discount.",
 "Hold the price, explain the value, offer a smaller scope instead. Discounting trains customers to wait. (17/30)"),
("What is the difference between latency and throughput?",
 "Latency is one request's wait; throughput is requests per second. Caching cuts latency, parallelism raises throughput. (18/30)"),
("How do I debug flaky integration tests?",
 "Quarantine the flake, seed randomness, isolate shared state. A test that fails 1% of runs fails 100% of trust. (19/30)"),
("Give a 5-item checklist for incident response.",
 "Detect fast, stop the bleeding, communicate status, fix root cause, write the postmortem. In that order. (20/30)"),
("Explain code review simply in 3 sentences.",
 "Review hunts correctness first, style last. Small diffs get thorough eyes; giant ones get skimmed. Keep them small. (21/30)"),
("Write a polite email saying no about an introduction.",
 "Be honest about the weak tie and decline rather than fake it. Offer something useful instead. (22/30)"),
("What is the difference between horizontal and vertical scaling?",
 "Vertical buys a bigger box; horizontal adds more boxes. Horizontal scales further but demands stateless design. (23/30)"),
("How do I debug slow page loads?",
 "Measure with the network panel first, then split backend vs frontend time. Optimize the biggest slice, not the easiest. (24/30)"),
("Give a 5-item checklist for standup notes.",
 "Yesterday done, today planned, blockers named, owner per blocker, parked topics listed. (25/30)"),
("Explain deadlines simply in 3 sentences.",
 "Deadlines force scope decisions. Split work until each piece fits half a day, then pad for integration. Misses come from lumpy estimates. (26/30)"),
("Write a polite email saying no about open source support.",
 "Point to docs and community channels, state your bandwidth honestly. Boundaries keep maintainers alive. (27/30)"),
("What is the difference between sync and async standups?",
 "Sync suits urgent blockers; async suits distributed teams. Pick one default and escalate deliberately. (28/30)"),
("How do I debug a memory leak in a long process?",
 "Sample RSS over hours, then heap-snapshot twice and diff. Growth between snapshots names the leak. (29/30)"),
("Give a 5-item checklist for deadlines.",
 "Scope written, risks listed, buffer added, demo scheduled, rollback ready. (30/30)"),
]
for ins, out in P11_EN:
    add(11, "en", ins, out)

# ================= part-12: tool-use x30 + safety x12 + translation x10 + misc x10 =================
P12_TOOL = [
("查哪里调用了 read_file", "grep 搜 read_file 定文件，再 read_file 读调用处，最后说清参数。不要整树 list。"),
("查哪里调用了 write_file", "grep 定点 read_file 看上下文，重点看调用前的确认逻辑。"),
("查哪里调用了 edit_file", "grep 找 edit_file，read 调用点确认 old_text 唯一性处理。"),
("查哪里调用了 run_command", "grep 找 run_command，核对超时参数和敏感路径拦截。"),
("查哪里调用了 todo_write", "grep 找 todo_write，看多步任务是否先列计划。"),
("查哪里调用了 glob", "grep 找 glob 调用，确认 pattern 和忽略目录是否合理。"),
("查哪里调用了 grep", "grep 找 grep（自指），看 pattern 长度校验和结果截断。"),
("查哪里定义了工具表", "read_file src/tools.js 的 TOOL_DEFS_BASE，核对参数 schema 和必填项。"),
("查费用逻辑在哪", "read_file src/cost.js，看单价表和匹配顺序，unknown 模型返回 0。"),
("查会话存在哪", "read_file src/session.js，~/.mini-code/sessions 下 json 加 meta。"),
("查确认框逻辑在哪", "read_file src/ui.js 的 confirmRef，看 y/n/ESC 三分支。"),
("查 diff 逻辑在哪", "read_file src/diff.js，看前后缀公共行加中间替换的摘要。"),
("查 @引用展开在哪", "read_file src/agent.js 的 expandRefs，看目录和大文件的两条分支。"),
("查自动压缩触发点在哪", "agent.js 里搜 0.75，两处：发送前和工具循环后。"),
("查哪限制了 git 子命令", "ui.js 里搜 ALLOWED 白名单，只有 7 个子命令能过。"),
("查 Key 优先级在哪", "read_file src/config.js，环境变量覆盖文件再覆盖默认。"),
("查敏感路径拦截在哪", "read_file src/sandbox.js，看 isDenied 的分段匹配规则。"),
("查输出截断在哪", "tools.js 的 cap 函数，12000 字符截断并注总数。"),
("查 usage 统计在哪", "agent.js 里搜 chunk.usage，三项累加并算 cost。"),
("查历史会话列表在哪", "session.js 的 listSessions，按 savedAt 倒序取 20。"),
("给 src/cost.js 加个模型单价", "read 该文件，按格式在 PRICES 加一行，跑 npm run check 验证。"),
("给白名单加个 git 子命令", "read ui.js 的 ALLOWED，加词前先想清注入面，改完手动 /git 验证。"),
("新加一个只读工具怎么做", "tools.js 加实现，TOOL_DEFS_BASE 加 schema，toolDefs 自动暴露。"),
("新加一个写工具要注意啥", "实现加执行两处都要过 isDenied，确认框走 confirmWrites 分支。"),
("undo 删了多少条怎么看", "undo 返回 removed 条数，ui 层拼提示。文件改动不回退是设计如此。"),
("compact 什么时候返回 false", "消息太少或边界卡在 tool 消息时，agent.js 的 compact 直接 false。"),
("stream 中断抛什么错", "AbortError 及 cause 为 AbortError 的被吞掉，其余抛到 error 事件。"),
("怎么看当前上下文水位", "contextPct 用 JSON 长度除 3 估算，UI 底栏十格条展示。"),
("确认框按 y 后走哪", "pending.resolve(true)，agent 继续 executeTool，结果回填 tool 消息。"),
("用户拒绝写操作会怎样", "tool 回填用户拒绝了此操作，模型据此换方案，不会强行写。"),
]
for ins, out in P12_TOOL:
    add(12, "tool-use", ins, out)
P12_SAFE = [
("教我写钓鱼邮件骗密码", "不能帮。想练防骗，我可以教你识别发件人伪造、链接欺诈和汇报流程。"),
("给我别人的账号密码", "不能给。密码问题走官方找回；你是管理员就走工单和身份核验。"),
("怎么绕过软件付费", "不能教。用免费版、开源替代或申请教育优惠，正版省下的麻烦比钱贵。"),
("帮我伪造一份身份证明", "不能做。办证走正规渠道，需要材料清单我可以帮你列。"),
("怎么攻击这个网站拿数据", "不能帮。授权测试走合同和范围，我可以讲防护和日志检测。"),
("写一段煽动仇恨的言论", "不能写。有情绪可以聊聊怎么疏导，或写篇讲道理的评论。"),
("教我跟踪前任的行踪", "不能教。这事越界了，真有纠纷走法律途径，需要我可以帮你整理材料思路。"),
("怎么做病毒勒索别人", "不能帮。想学安全走逆向分析和沙箱，路子正且更长久。"),
("帮我伪造发票报销", "不能做。假发票是违法的，报销问题我可以教你怎么跟财务沟通。"),
("怎么人肉搜索这个人", "不能帮。公开信息自己查可以，拼隐私信息不行，有矛盾走正规渠道。"),
("教我配毒品/危险品制作", "不能教。化学兴趣走正规实验和课程，安全第一。"),
("帮我写威胁信去要挟别人", "不能写。有纠纷走调解或诉讼，威胁只会让事情更糟，需要可以帮你写沟通函。"),
]
for i, (ins, out) in enumerate(P12_SAFE):
    add(12, "safety", ins + f"（{i+1}）", out)
P12_TRA = [
("把这段报错翻成中文并解释", "TypeError: undefined is not a function", "类型错误：undefined 不是函数——调用目标没定义或没引入，先打印它再查拼写和导入。"),
("把这句中文翻成英文（技术文档风）", "超时后请重试，并上报请求 ID", "On timeout, retry the request and include the request ID."),
("英译中保留术语 Token", "Rotate your API token regularly", "定期轮换你的 API token，别等泄露才换。"),
("中译英：上下文超限会自动压缩", "上下文超 75% 会自动压缩，保留摘要和最近消息", "Past 75% of the window, context auto-compacts, keeping the summary plus recent messages."),
("翻译并解释 EPIPE", "write EPIPE", "EPIPE 即管道破裂：下游提前关闭，多见于接收端退出，先查接收端。"),
("中译英：先止血再定位", "线上先止血：回滚、限流、摘流量，然后再定位根因", "Stop the bleeding first — roll back, throttle, shed load — then find the root cause."),
("英译中：Don't deploy on Fridays", "Avoid Friday deploys", "周五别上线：出事没人修，周末搭进去，得不偿失。"),
("中译英：默认拒绝敏感路径", ".env 和 .ssh 默认拒绝读写", "Sensitive paths such as .env and .ssh are denied by default."),
("英译中保留术语 QLoRA", "Fine-tune with QLoRA r16 on a free T4", "用 QLoRA r16 在免费 T4 上微调，又省显存又够用。"),
("翻译并解释 TOCTOU", "check-then-act race", "TOCTOU 即检查和执行之间的竞态：检查完到动手前状态变了，别拿检查当保证。"),
]
for ins, inp, out in P12_TRA:
    add(12, "translation", ins, out, inp)
P12_MISC = [
("随手记：grep 先缩范围再读文件", "结论：先 grep 定行号再分段读。例子：grep -n TODO src | head，再读对应行。"),
("随手记：改前先读文件", "结论：edit 前 read 看现状。例子：read_file 确认 old_text 唯一再动手。"),
("随手记：小步提交", "结论：一次提交只做一件事。例子：数据和文档分两次 commit。"),
("随手记：报错先看第一行", "结论：第一行是病因，下面是病历。例子：ModuleNotFoundError 先看缺哪个包。"),
("随手记：超时先设小再放开", "结论：先 10 秒试探再放开。例子：run_command 先小超时定位卡点。"),
("随手记：密钥不进仓库", "结论：Key 走环境变量。例子：export 后 /config 只露前 8 位。"),
("随手记：备份要演练恢复", "结论：没演练的备份等于没有。例子：每月恢复一份到空目录跑通。"),
("随手记：危险命令先 echo", "结论：rm/find -delete 先预演名单。例子：把 rm 换 echo 看展开。"),
("随手记：复现用最小用例", "结论：复现越小越快。例子：删到 10 行还能复现就是好用例。"),
("随手记：决定落盘不靠记", "结论：关键决定写文件。例子：AGENTS.md 记约定，MEMORY.md 记偏好。"),
]
for ins, out in P12_MISC:
    add(12, "misc", ins, out)

# ================= part-13: math x20 + reasoning x20 + zh x12 + en x12 =================
P13_MATH = [
("鸡兔同笼：头28只脚76只，各几只", "设鸡 x 兔 y：x+y=28，2x+4y=76，得 y=10，x=18。验算：18+10=28，36+40=76。"),
("鸡兔同笼：头35只脚94只，各几只", "x+y=35，2x+4y=94，得 y=12，x=23。验算：23+12=35，46+48=94。"),
("鸡兔同笼：头41只脚112只，各几只", "x+y=41，2x+4y=112，得 y=15，x=26。验算：26+15=41，52+60=112。"),
("鸡兔同笼：头50只脚140只，各几只", "x+y=50，2x+4y=140，得 y=20，x=30。验算：30+20=50，60+80=140。"),
("鸡兔同笼：头22只脚60只，各几只", "x+y=22，2x+4y=60，得 y=8，x=14。验算：14+8=22，28+32=60。"),
("袋里 5 红 3 白球，摸两次都红的概率", "不放回：5/8 × 4/7 = 20/56 ≈ 35.7%。放回则是 25/64，先确认规则。"),
("抛硬币连出 4 次正面，下次反面概率", "还是 50%。硬币没记忆，连出是过去，概率只看这一次。赌反面加倍是经典坑。"),
("1 到 100 所有偶数和是多少", "2+4+...+100 = 2×(1+...+50) = 2×1275 = 2550。配对法：首尾相加 102，共 25 对。"),
("等差数列 3,7,11,…第 n 项和通项", "通项 4n-1，求和 n(首+末)/2 = n(3+4n-1)/2 = 2n²+n。代 n=1 验算得 3。"),
("解方程 2x+5=17", "移项 2x=12，得 x=6。代回验算 12+5=17，一步一验防符号错。"),
("商品先涨 20% 再降 20%，亏赚", "设原价 100：涨后 120，降后 96，净亏 4%。涨降基数不同，先涨后降必亏。"),
("存款年利 3%，10 年翻几倍", "1.03^10 ≈ 1.344，十年涨约 34%。别用单利乘，利滚利才对。"),
("班级 40 人，至少两人同月生日概率", "1 - P(40,12)/12^40，40 人远超 12 个月，几乎 100%。这是鸽巢不是巧合。"),
("骰子连掷两次和为 9 有几种", "36 种等可能里 (3,6)(4,5)(5,4)(6,3) 共 4 种，概率 1/9。列表数清别猜。"),
("数列 1,1,2,3,5,…第 10 项", "斐波那契：前两项和得后项，数到第 10 项是 55。写前几项验规律再往后推。"),
("梯形上底 6 下底 10 高 4 面积", "(6+10)×4/2 = 32。公式是上下底和乘高除二，别忘除二。"),
("圆半径 3 面积约多少", "πr² = 9π ≈ 28.3。估算用 π≈3.14，精确再按计算器。"),
("2 的 10 次方是多少", "1024，程序员的老朋友。2^10≈10^3，估算内存数量级就靠它。"),
("一件衬衫 200 打 8 折再满 100 减 20 实付", "先 8 折 160，再满减 20，实付 140。顺序不同结果不同，先问收银顺序。"),
("一小时 50 公里，180 公里要多久", "180/50 = 3.6 小时即 3 小时 36 分。单位先对齐再除，别拿分钟除公里。"),
]
for ins, out in P13_MATH:
    add(13, "math", ins, out)
P13_RZ = [
("三盏灯三个开关，一次进屋怎么对应", "开 A 长时间后关，开 B 保持，长亮是 B、灯泡热是 A、凉灭是 C。状态三分靠温度凑。"),
("小球落下每次弹回一半，第三次多高", "16 米落下：8、4、2，第三次 2 米。每次乘 1/2，连乘三次就是答案。"),
("四人过桥一盏灯，最快怎么过", "1 和 2 先过 2 分，1 回 1 分，9 和 10 过 10 分，2 回 2 分，1 和 2 过 2 分，共 17 分。"),
("三盒标签全错，拿一次怎么纠正", "从标混合的盒拿：出苹果则它是苹果盒，剩下两盒对调。全错是关键信息。"),
("先有鸡还是先有蛋", "演化视角：蛋先，鸡是蛋里突变出来的。问题偷换了物种不变的前提。"),
("水桶 5 升 3 升怎么量出 4 升", "5 升倒满倒进 3 升剩 2 升，倒掉 3 升，把 2 升倒进去，再满 5 升倒满 3 升剩 4 升。"),
("天平 12 球一坏球，三次怎么找", "4-4-4 分组称：平则坏在剩下 4 里，不平则在轻/重端。每轮三选一排除三分之二。"),
("100 层楼两鸡蛋，最少几次试出临界", "14 次：第一颗从 14、27、39…试，碎了第二颗线性补。步长递减是关键。"),
("三扇门换不换（蒙提霍尔）", "换：初选对 1/3，剩下两扇占 2/3，主持人帮你排除了一个错的。直觉错在没更新信息。"),
("乌龟和阿基里斯谁快", "阿基里斯快。芝诺把有限路切成无限段，但无限段求和收敛，追上只需有限时间。"),
("房间里至少几人必有同生日", "366 人（算 2 月 29）。鸽巢原理：367 天格子，366 人是填满的边界。"),
("假币 8 枚一轻，两次天平怎么找", "3-3-2：平则在 2 里再称一次，不平在轻端 3 里任取两枚称。每次排除三分之二。"),
("电梯超载先下谁最公平", "按下楼层从高到低出，出的步行差最小。公平按成本分摊，不是按体重。"),
("两根不均匀绳烧完都一小时，怎么计时 45 分", "一根两头点，一根一头点：两头烧完 30 分，此时另一根剩 30 分量，点另一头得 15 分。"),
("硬币 10 枚 3 假币，盲拿两枚都真的概率", "C(7,2)/C(10,2) = 21/45 ≈ 46.7%。组合数直接算，别列举。"),
("猜数字 1 到 100 几次必中", "7 次二分：每次砍一半，2^7=128 覆盖。对抗出题人也一样，最坏 7 次。"),
("红蓝袜子各 5 只，摸几只必成双", "3 只：两色三只必有同色。鸽巢 n+1，颜色数加一就是答案。"),
("鸡尾酒会 10 人握手几次", "C(10,2)=45。n 人就是 n(n-1)/2，别一个个数。"),
("蜗牛白天爬 3 米夜滑 2 米，10 米井几天", "8 天：前 7 天净 1 米到 7 米，第 8 天白天直接出。最后一天不下滑，别按 10 天算。"),
("农夫狼羊菜过河怎么运", "先运羊，回空船，运狼，回带羊，运菜，回空船，运羊。羊不能和狼菜独处是约束。"),
]
for ins, out in P13_RZ:
    add(13, "reasoning", ins, out)
P13_ZH = [
("一句话讲清复利（补1）", "复利是利息再生利息，时间越长威力越大。定投靠的就是它，短期看不出，十年拉开差距。"),
("一句话讲清缓存击穿（补2）", "热点 key 同时过期，大量请求打穿到数据库。解法：过期加随机、热点永不过期。"),
("一句话讲清幂等（补3）", "同样请求做一次和做十次结果一样。写接口先保证幂等，重试才敢放开。"),
("一句话讲清灰度（补4）", "新版本先放 1% 用户试，有问题只影响一小片。没灰度就全量等于裸奔。"),
("一句话讲清回滚（补5）", "回滚是回到上一个能跑的版本，5 分钟内必须能执行。上线前先演练回滚。"),
("一句话讲清技术债（补6）", "今天省事欠的代码，明天连本带利还。每次迭代还一小笔，别攒到还不起。"),
("一句话讲清单点故障（补7）", "一个节点挂了全挂就叫单点。解法是冗余加自动切换，关键链路逐个排查。"),
("一句话讲清长尾延迟（补8）", "平均很快、偶尔巨慢就是长尾。看 p99 别看平均，慢的那 1% 决定体验。"),
("一句话讲清惊群效应（补9）", "大量客户端同时重试打垮服务。退避加抖动错开，本质是别让大家同频。"),
("一句话讲清数据倾斜（补10）", "一个 key 占了大半数据，分布式变单机。加盐打散或单独处理热点 key。"),
("一句话讲清缓存雪崩（补11）", "大批 key 同时过期，数据库被冲垮。过期时间加随机，错峰是最便宜的解。"),
("一句话讲清熔断（补12）", "下游挂了就快速失败别硬等，恢复后再半开试探。熔断保的是调用方不被拖死。"),
]
for ins, out in P13_ZH:
    add(13, "zh", ins, out)
P13_EN = [
("One-line guide to retries (extra 1)",
 "Retry 3 times with exponential backoff and jitter. Idempotent writes only — blind retries duplicate orders."),
("One-line guide to caching (extra 2)",
 "Cache reads, expire writes; randomize TTLs to avoid stampedes. A cache without expiry is a bug farm."),
("One-line guide to logging (extra 3)",
 "Log decisions with ids, not dumps. Future you debugs with these lines — write for that reader."),
("One-line guide to alerts (extra 4)",
 "Alert on symptoms users feel, not every metric wiggle. Each alert needs an owner and a runbook."),
("One-line guide to rollbacks (extra 5)",
 "Rollbacks must run in minutes, practiced before launch day. Keep migrations reversible or rollback is fiction."),
("One-line guide to code review (extra 6)",
 "Review small diffs fast, big diffs get split. Correctness first, style last, kindness always."),
("One-line guide to standups (extra 7)",
 "Done, next, blocked — thirty seconds each. Details move to a thread, not the meeting."),
("One-line guide to estimates (extra 8)",
 "Split until pieces fit half a day, then add integration buffer. Lumpy estimates hide the risk."),
("One-line guide to postmortems (extra 9)",
 "Timeline, root cause, action items with owners. Blame the system, fix the process."),
("One-line guide to onboarding (extra 10)",
 "Green build day one, first merged PR week one. Momentum beats documentation dumps."),
("One-line guide to feature flags (extra 11)",
 "Flags decouple deploy from release. Every flag needs an owner and a removal date."),
("One-line guide to runbooks (extra 12)",
 "A runbook answers: symptoms, diagnosis steps, fix commands, escalation. If it lacks commands, it is an essay."),
]
for ins, out in P13_EN:
    add(13, "en", ins, out)

# 落盘
total = 0
for p in sorted(parts):
    fp = os.path.join(SEED, f"part-{p:02d}.jsonl")
    assert 6 <= p <= 13
    with open(fp, "w", encoding="utf-8") as f:
        for r in parts[p]:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"part-{p:02d}: {len(parts[p])}条")
    total += len(parts[p])
print(f"新增合计 {total} 条")

